// term-needs.test.mjs (lane G5-NEED, 2026-10-07): the pure need planner, proven on fixtures.
import test from "node:test";
import assert from "node:assert/strict";
import {
  needTextFor, holdingQualifies, planTermNeeds, celexOf, planLineageNeeds, termNeedRow, TERM_NEED_RULE,
} from "./term-needs.mjs";

const T1 = "11111111-0000-4000-8000-000000000001";
const T2 = "11111111-0000-4000-8000-000000000002";
const T3 = "11111111-0000-4000-8000-000000000003";
const term = (id, over = {}) => ({ id, kind: "standard", term_key: `key ${id.slice(-1)}`, label: `Label ${id.slice(-1)}`, status: "adopted", distinct_items: 3, distinct_sources: 2, ...over });
const item = (id, over = {}) => ({ id, item_type: "regulation", provenance_status: "verified", is_archived: false, origin_class: "primary", source_id: `s-${id}`, ...over });
const sourceMap = (rows) => new Map(rows.map((s) => [s.id, s]));

test("needTextFor: generated by rule from kind and label, deterministic, no dash glyphs", () => {
  assert.equal(needTextFor("standard", "ISO 14083"), "ISO 14083 standard authoritative source");
  assert.equal(needTextFor("material", "  recycled   aluminium "), "recycled aluminium material authoritative source");
  assert.equal(needTextFor("standard", "ISO 14083"), needTextFor("standard", "ISO 14083"));
  for (const k of ["standard", "material", "theme", "scenario", "compliance_object", "term"]) {
    assert.match(needTextFor(k, "x"), /^x [a-z ]+ authoritative source$/);
  }
});

test("holdingQualifies: base tier (or its tier_override) at or above the item type authority floor, verified, live, not community", () => {
  const src = (tier) => ({ id: "s-x", base_tier: tier, effective_tier: 1 });
  assert.equal(holdingQualifies(item("x", { source_id: "s-x" }), src(2)), true, "regulation floor 2, tier 2");
  assert.equal(holdingQualifies(item("x", { source_id: "s-x" }), src(3)), false, "tier 3 is below the regulation floor");
  assert.equal(holdingQualifies(item("x", { item_type: "research_finding", source_id: "s-x" }), src(4)), true, "research floor 4");
  assert.equal(holdingQualifies(item("x", { item_type: "research_finding", source_id: "s-x" }), src(5)), false);
  assert.equal(holdingQualifies(item("x", { item_type: "market_signal", source_id: "s-x" }), src(6)), true, "a type with no floor needs only a rated source");
  assert.equal(holdingQualifies(item("x", { source_id: "s-x" }), { id: "s-x", base_tier: 5, tier_override: 2 }), true, "the sanctioned per-host override counts");
  assert.equal(holdingQualifies(item("x", { source_id: "s-x" }), { id: "s-x", base_tier: 5, effective_tier: 1 }), false, "dynamic effective_tier never confers eligibility (moat, SC-9)");
  assert.equal(holdingQualifies(item("x", { source_id: "s-x" }), { id: "s-x", base_tier: null }), false, "an unrated source never qualifies");
  assert.equal(holdingQualifies(item("x", { source_id: null }), src(1)), false, "no primary source");
  assert.equal(holdingQualifies(item("x", { source_id: "s-x", is_archived: true }), src(1)), false);
  assert.equal(holdingQualifies(item("x", { source_id: "s-x", provenance_status: "unverified" }), src(1)), false);
  assert.equal(holdingQualifies(item("x", { source_id: "s-x", origin_class: "community" }), src(1)), false, "ADR-041");
  assert.equal(holdingQualifies(item("x", { source_id: "s-x", origin_class: "community-corroborated" }), src(1)), false);
  assert.equal(holdingQualifies(null, src(1)), false);
  assert.equal(holdingQualifies(item("x", { source_id: "s-x" }), null), false);
});

test("planTermNeeds: an adopted term with no authoritative holding raises exactly one need", () => {
  const items = new Map([["i1", item("i1")], ["i2", item("i2")]]);
  const sources = sourceMap([{ id: "s-i1", base_tier: 5 }, { id: "s-i2", base_tier: 3 }]);
  const mentions = [{ term_id: T1, item_id: "i1" }, { term_id: T1, item_id: "i2" }, { term_id: T1, item_id: "i2" }];
  const plan = planTermNeeds({ terms: [term(T1)], mentions, items, sources });
  assert.equal(plan.fresh.length, 1);
  const { subjectRef, row } = plan.fresh[0];
  assert.equal(subjectRef, T1);
  assert.deepEqual([row.created_by, row.status, row.category, row.subject_type, row.subject_ref], ["term-need:standard", "open", "coverage_gap", "system", T1]);
  const act = row.recommended_actions[0];
  assert.equal(act.action, "find-source");
  assert.equal(act.need, needTextFor("standard", "Label 1"));
  assert.equal(act.term_id, T1);
  assert.equal(act.rule, TERM_NEED_RULE);
  assert.equal(plan.counts.needs, 1);
  assert.equal(plan.counts.satisfied, 0);
});

test("planTermNeeds: an adopted term WITH an authoritative holding raises none", () => {
  const items = new Map([["i1", item("i1")], ["i2", item("i2")]]);
  const sources = sourceMap([{ id: "s-i1", base_tier: 5 }, { id: "s-i2", base_tier: 2 }]);
  const mentions = [{ term_id: T1, item_id: "i1" }, { term_id: T1, item_id: "i2" }];
  const plan = planTermNeeds({ terms: [term(T1)], mentions, items, sources });
  assert.equal(plan.fresh.length, 0);
  assert.equal(plan.counts.satisfied, 1);
});

test("planTermNeeds: proposed and retired terms never raise a need; an adopted term with no mentions raises one", () => {
  const plan = planTermNeeds({
    terms: [term(T1, { status: "proposed" }), term(T2, { status: "retired" }), term(T3)],
    mentions: [], items: new Map(), sources: new Map(),
  });
  assert.deepEqual(plan.fresh.map((f) => f.subjectRef), [T3]);
  assert.equal(plan.counts.adopted_terms, 1);
});

test("planTermNeeds: a mention of an item that is not eligible (not in the items map) does not count as holding", () => {
  const plan = planTermNeeds({ terms: [term(T1)], mentions: [{ term_id: T1, item_id: "gone" }], items: new Map(), sources: new Map() });
  assert.equal(plan.fresh.length, 1);
});

test("termNeedRow: description is capped and carries no dash glyph", () => {
  const row = termNeedRow({ term: term(T1, { label: "L".repeat(900) }), need: "n".repeat(900), counts: { distinct_items: 3, distinct_sources: 2 } });
  assert.ok(row.description.length <= 480);
  assert.ok(!new RegExp("[" + String.fromCharCode(0x2013, 0x2014) + "]").test(row.description));
});

test("celexOf: CELEX ids (bare or prefixed, any case) normalise to uppercase; a bare year/number is not one", () => {
  assert.equal(celexOf("32023R1805"), "32023R1805");
  assert.equal(celexOf("celex:32019r1242"), "32019R1242");
  assert.equal(celexOf("CELEX 32019R1242"), "32019R1242");
  assert.equal(celexOf("2023/1805"), null);
  assert.equal(celexOf(""), null);
  assert.equal(celexOf(null), null);
});

test("planLineageNeeds: CELEX targets go to the register walker list, every other shape becomes a standard need", () => {
  const targets = [
    { identifier: "32023R1805", relationship: "implements", citing_item_id: "a", flag_id: "f1" },
    { identifier: "32023R1805", relationship: "amends", citing_item_id: "b", flag_id: "f2" },
    { identifier: "2019/1242", relationship: "implements", citing_item_id: "a", flag_id: "f1" },
    { identifier: "2019/1242", relationship: "depends_on", citing_item_id: "c", flag_id: "f3" },
  ];
  const plan = planLineageNeeds(targets);
  assert.deepEqual(plan.celex, ["32023R1805"], "distinct, uppercase");
  assert.equal(plan.fresh.length, 1);
  const { subjectRef, row } = plan.fresh[0];
  assert.equal(subjectRef, "lineage:2019/1242");
  assert.equal(row.created_by, "term-need:standard");
  assert.equal(row.recommended_actions[0].kind, "standard");
  assert.deepEqual(row.recommended_actions[0].citing_item_ids, ["a", "c"]);
  assert.equal(row.recommended_actions[0].need, needTextFor("standard", "2019/1242"));
  assert.deepEqual(plan.counts, { distinct_identifiers: 2, celex_targets: 1, non_celex_needs: 1 });
});

test("planLineageNeeds: no targets, no needs", () => {
  assert.deepEqual(planLineageNeeds([]).fresh, []);
  assert.deepEqual(planLineageNeeds(undefined).celex, []);
});
