-- ════════════════════════════════════════════════════════════════════
-- Migration 015 — provisional_sources.recommended_classification
--
-- Phase B.0e adds an AI-recommended classification flow for provisional
-- sources. The recommendation runs once per provisional via the new
-- /api/admin/sources/recommend-classification route and is cached on the
-- row so the SourceHealthDashboard provisional view doesn't re-call the
-- model on every render. The cache also captures the model rationale
-- for reviewer context.
--
-- Apply via the Supabase Dashboard SQL Editor — DDL cannot run through
-- @supabase/supabase-js.
--
-- Rollback: DROP COLUMN provisional_sources.recommended_classification;
-- (no data is lost beyond cached recommendations, which can be
-- regenerated by the route).
-- ════════════════════════════════════════════════════════════════════

ALTER TABLE provisional_sources
  ADD COLUMN IF NOT EXISTS recommended_classification JSONB;

COMMENT ON COLUMN provisional_sources.recommended_classification IS
  'AI-recommended classification produced by /api/admin/sources/recommend-classification. Schema: { tier: 1..7, domains: int[], jurisdictions: text[], transport_modes: text[], topic_tags: text[], rationale: text, model: text, computed_at: ISO timestamp }. Null until the route runs for this row. Cleared if the row''s URL changes.';
