-- subject: Migration 381 (lane SEC-7, 2026-10-08): write policies name their role; every INSERT, UPDATE, DELETE and ALL policy in public whose roles were the implicit {public} and whose predicate only an authenticated actor or the service role can satisfy (auth.uid(), auth.role() = 'service_role' or 'authenticated', or one of the helpers user_org_role, user_group_role, user_can_write_in_org, user_belongs_to_org, user_is_group_admin, user_owns_group, is_platform_admin) is ALTERed TO authenticated, service_role (111 policies: 107 read from the migration tree and listed one by one, 4 out-of-band policies found at apply time), so anon no longer needs the table-level INSERT, UPDATE and DELETE that migration 369 left on every table whose policy was TO public; 369's grant hygiene block is run again verbatim after the ALTERs and anon ends with no write privilege on any public table; anon's refusal on those tables now comes from the GRANT (permission denied for table), not from a revoked EXECUTE on a policy helper; a rolled-back self-check attacks every touched table as anon for all three commands and proves the real principals (member, viewer, group admin, org owner, service role) still behave as before; APPLIED (production ledger version 20261008232035, as of 2026-10-08).
-- 381 -- write policies name their role (lane SEC-7, 2026-10-08).
--
-- APPLIED (production ledger version 20261008232035, as of 2026-10-08). Authored by lane SEC-7; the coordinator's executor applies it after CI (two-track policy, CLAUDE.md
-- standing rule 3: schema DDL applies via the Supabase CLI before any dependent code commits). No code in src or
-- scripts changes. Sibling of 369 (SEC-3a, grant hygiene) and 370 (SEC-3b, the policies in question), 371 (SEC-4, the
-- helpers' grants, which this file does not touch) and 375 (SEC-6, is_platform_admin()).
--
-- THE FINDING [CONFIRMED by AUD-AT-1, fsi-app/scripts/tmp/aud-at1-rls-grants-attacked-2026-10-08.md section 11, a rolled
-- back catalog probe against the live schema; 0 ACCEPTED of 1210 cells]. A policy written without a TO clause is TO
-- public. Migration 369 re-granted anon table-level INSERT, UPDATE and DELETE on exactly the tables that carry such a
-- policy (a policy whose roles overlap {anon, public} still needs the grant), so anon held those privileges on 44, 35
-- and 31 tables although no anon request could ever satisfy the policy: every one of these policies tests auth.uid(),
-- auth.role() or a helper that keys on auth.uid(). For 19 of the 24 anon cells that have an applicable policy the
-- refusal came from the revoked EXECUTE privilege on the helper (user_org_role, user_group_role,
-- user_can_write_in_org: "permission denied for function"), not from the policy and not from the table grant. That is
-- a side effect, not a guard, and it is the wrong guard for a second reason: migration 375 had to grant
-- is_platform_admin() to anon because an OR'd policy raises 42501 when its helper is revoked from the evaluating role.
-- ADR-046 (constructive over detective) says the property is carried by the object: the policy names the roles it
-- applies to, and the table grant follows from the policies (369 already derives it that way).
--
-- THE FIX, IN FOUR PARTS.
--   1. EXPLICIT LIST. One ALTER POLICY ... TO authenticated, service_role per policy, generated by reading the
--      migration tree (final state after every CREATE, ALTER, DROP and RENAME of a policy, in file order, below 381):
--      every policy with cmd INSERT, UPDATE, DELETE or ALL whose roles are the implicit {public} (107). ALL is included
--      because it applies to the three write commands and 369's re-grant keys on ALL as well as on the named commands.
--      The list is reviewable here and a test re-derives it from the tree and fails on any difference. Semantics
--      are unchanged for every real principal: a policy TO public applies to every role, a policy TO authenticated,
--      service_role applies to those two; anon (a request with no sub claim) cannot satisfy a predicate built on
--      auth.uid() (NULL), auth.role() = 'service_role' or 'authenticated' (it is 'anon') or a helper that keys on
--      auth.uid(); the service role bypasses RLS; the one other role with its own policies, reconciler, connects
--      directly with no JWT (migration 118: auth.role() is NULL for it) and has policies TO reconciler of its own.
--      A precondition checks each listed policy at apply time: it exists, has roles {public} (or is already narrowed,
--      which makes a re-run a no-op), and its live predicate still names an authenticated actor; otherwise the apply
--      stops before any change.
--   2. OUT-OF-BAND POLICIES. Four write policies exist only in the live database, recorded by no migration file
--      (docs/inventories/out-of-band-objects.md): summaries_write_service and summaries_update_service on
--      intelligence_summaries, changes_write_service on intelligence_changes, sector_contexts_write_service on
--      sector_contexts. AT1 shows each applies to anon (pp1) and refuses it on the policy (R:rls or R0). They are named
--      here and narrowed by a guarded DO block: only when present, only when the live predicate requires an
--      authenticated actor (migration 259 rewrote the two summaries predicates to auth.role() = 'service_role'; the
--      other two predicates are not in the tree, so they are read from pg_policies at apply time and the apply stops if
--      one is satisfiable by anon).
--   3. THE ENUMERATION AS ASSERTION. After the ALTERs the block reads pg_policies: no policy in public with a write
--      command and roles = {public} may remain on a table whose write policies (those that apply to anon or public)
--      all require an authenticated actor. A policy this migration missed fails the apply and is named in the error.
--   4. GRANT HYGIENE, AGAIN. The block of migration 369 section 3 is repeated here verbatim (same statements, same
--      invariants) AFTER the ALTERs, so anon loses table-level INSERT, UPDATE and DELETE on every table that no
--      longer carries an anon-or-public write policy. Order matters and is the reason the block is repeated rather than
--      called: run before the ALTERs it would re-grant the privileges (the policies still overlap {public}). 369 did
--      not define a function, so the block is copied, not called.
--
-- WHAT STAYS. Tables that legitimately keep an anon write policy: none. [CONFIRMED by the tree parse in the test file
-- and by the live pp counts of AT1: 106 of 110 anon write cells with an applicable policy match the tree, the other
-- four are exactly the out-of-band policies of part 2.] The block still handles one if it ever exists: a table with a
-- write policy that anon could satisfy keeps its grant, is not touched by part 1, and is named in a NOTICE.
-- SELECT policies and grants are not touched (anon SELECT is a read decision, not this lane's). The helpers' own
-- grants are SEC-4 (371), not this file; after this file the write policies are no longer evaluated for anon at all,
-- so the anon EXECUTE on is_platform_admin() that 375 needed for OR'd evaluation is no longer needed by a write policy
-- (a SELECT policy may still need it).
--
-- SELF-CHECK. One DO block, no row survives (a sentinel exception rolls it back), fixtures are real auth.users and
-- profiles rows plus an organization, memberships, a community group and the rows under test, all created as the
-- migration role. If the fixture insert fails the fixture legs are skipped with a NOTICE and the catalog and per-table
-- attack legs still run. Legs: (A) the catalog: every listed policy has roles {authenticated, service_role}; the
-- enumeration assertion of part 3; anon holds no INSERT, UPDATE or DELETE (table or column level) on any public table
-- unless a policy that applies to anon justifies it; (B) for EVERY table in the list, anon INSERT, UPDATE and DELETE
-- must raise 42501 with the message "permission denied for table <name>" (the grant, not a function and not a policy);
-- (C) fixtures: anon is refused on the GRANT with a fully valid row on org_watchlist, workspace_tags, portfolios,
-- org_memberships, community_group_members and user_watchlist (the three helper families of AT1 section 11), an org
-- member still inserts into the workspace tables, an org owner still adds a member, a group admin still adds a group
-- member, a user still writes their own watchlist row, a viewer is still refused by the policy (row-level security,
-- not the grant), another user's row is still refused, and the service role still writes.
--
-- Reversible in intent (do not: it re-opens the grants): ALTER POLICY each of the listed policies back TO public and
-- re-run 369's re-grant loop.

BEGIN;

-- ---- Helper: does a predicate name an authenticated actor? -------------------------------------------------------
-- pg_policies prints qual and with_check in the deparsed form, so the idiom auth.role() = 'service_role' appears as
-- (( SELECT auth.role() AS role) = 'service_role'::text); the pattern allows a short gap between the call and the role
-- literal. A text match is necessary, not sufficient: the policy list was also read by eye (every predicate is an AND of
-- the actor test with the row test, or an OR of actor-keyed branches only), and the self-check attacks the result.
CREATE FUNCTION pg_temp.sec7_requires_auth(p_pred text) RETURNS boolean
LANGUAGE sql IMMUTABLE AS $f$
  SELECT coalesce(p_pred, '') ~* '(auth\.uid\(\)|auth\.jwt\(\)|auth\.role\(\).{0,60}(service_role|authenticated)|user_org_role|user_group_role|user_can_write_in_org|user_belongs_to_org|user_is_group_admin|user_owns_group|user_is_group_member|is_platform_admin)'
$f$;

-- ---- Preconditions -----------------------------------------------------------------------------------------------
DO $pre$
DECLARE
  v_list text[] := ARRAY[
    'admin_action_cooldowns.service role full access',
    'canonical_source_candidates.canonical_source_candidates_admin_write',
    'community_group_invitations.community_group_invitations_insert_admin',
    'community_group_invitations.community_group_invitations_service_role',
    'community_group_invitations.community_group_invitations_update_admin',
    'community_group_invitations.community_group_invitations_update_invitee',
    'community_group_members.community_group_members_delete_self_or_admin',
    'community_group_members.community_group_members_insert_admin',
    'community_group_members.community_group_members_service_role',
    'community_group_members.community_group_members_update_self_prefs',
    'community_groups.community_groups_delete_owner_or_admin',
    'community_groups.community_groups_insert_authenticated',
    'community_groups.community_groups_service_role',
    'community_groups.community_groups_update_owner_or_admin',
    'community_member_profiles.community_member_profiles_service_role',
    'community_member_profiles.community_member_profiles_update_own',
    'community_member_profiles.community_member_profiles_upsert_own',
    'community_post_signoff_requests.signoff_decide',
    'community_post_signoff_requests.signoff_insert',
    'community_post_signoff_requests.signoff_withdraw_own',
    'community_posts.community_posts_delete_author_or_admin',
    'community_posts.community_posts_insert_member',
    'community_posts.community_posts_service_role',
    'community_posts.community_posts_update_author_or_admin',
    'community_thread_entities.community_thread_entities_insert_author',
    'community_thread_entities.community_thread_entities_service_role',
    'community_topic_groups.community_topic_groups_delete_owner',
    'community_topic_groups.community_topic_groups_insert_owner',
    'community_topic_groups.community_topic_groups_service_role',
    'community_topics.community_topics_delete_owner',
    'community_topics.community_topics_insert_owner',
    'community_topics.community_topics_service_role',
    'community_topics.community_topics_update_owner',
    'connection_theme_runs.connection_theme_runs_admin_write',
    'connection_themes.connection_themes_admin_write',
    'holdings_quality.holdings_quality_service_role_write',
    'ingest_rejections.ingest_rejections_update_platform_admin',
    'integrity_flags.integrity_flags_admin_update',
    'integrity_flags.integrity_flags_service_role_write',
    'intelligence_items.intelligence_items_admin_delete',
    'intelligence_items.intelligence_items_admin_insert',
    'intelligence_items.intelligence_items_admin_update',
    'item_assignments.item_assignments_delete_party',
    'item_assignments.item_assignments_insert_member',
    'item_assignments.item_assignments_update_party',
    'item_changelog.item_changelog_admin_write',
    'item_cross_references.item_cross_references_admin_delete',
    'item_cross_references.item_cross_references_admin_write',
    'item_disputes.item_disputes_admin_update',
    'item_disputes.item_disputes_admin_write',
    'item_notes.item_notes_insert_member',
    'item_notes.item_notes_update_author_or_admin',
    'item_supersessions.item_supersessions_admin_write',
    'item_timelines.item_timelines_admin_update',
    'item_timelines.item_timelines_admin_write',
    'item_workspace_tags.item_workspace_tags_org_delete',
    'item_workspace_tags.item_workspace_tags_org_insert',
    'moderation_reports.moderation_reports_insert_authenticated',
    'moderation_reports.moderation_reports_service_role',
    'moderation_reports.moderation_reports_update_admin',
    'monitoring_queue.monitoring_queue_admin_update',
    'monitoring_queue.monitoring_queue_admin_write',
    'notification_preferences.notification_preferences_delete_self',
    'notification_preferences.notification_preferences_insert_self',
    'notification_preferences.notification_preferences_service_role',
    'notification_preferences.notification_preferences_update_self',
    'notifications.notifications_service_role',
    'notifications.notifications_update_self_read',
    'org_invitations.org_invitations_admin_insert',
    'org_invitations.org_invitations_admin_update',
    'org_invitations.org_invitations_service_role',
    'org_memberships.membership_delete_admin',
    'org_memberships.membership_update_admin',
    'org_memberships.membership_write_admin',
    'org_watchlist.org_watchlist_member_delete',
    'org_watchlist.org_watchlist_member_insert',
    'org_watchlist.org_watchlist_member_update',
    'organizations.org_update_admin',
    'organizations.org_write_service',
    'pending_jurisdiction_review.pjr_update_platform_admin',
    'portfolio_members.portfolio_members_org_delete',
    'portfolio_members.portfolio_members_org_insert',
    'portfolios.portfolios_org_delete',
    'portfolios.portfolios_org_insert',
    'portfolios.portfolios_org_update',
    'provisional_sources.provisional_sources_admin_update',
    'provisional_sources.provisional_sources_admin_write',
    'source_citations.source_citations_admin_write',
    'source_tier_opinions.source_tier_opinions_update_platform_admin',
    'source_trust_events.source_trust_events_admin_insert',
    'sources.sources_admin_delete',
    'sources.sources_admin_insert',
    'sources.sources_admin_update',
    'staged_updates.staged_updates_admin_update',
    'staged_updates.staged_updates_admin_write',
    'user_item_state.user_item_state_delete',
    'user_item_state.user_item_state_insert',
    'user_item_state.user_item_state_update',
    'user_watchlist.user_watchlist_delete',
    'user_watchlist.user_watchlist_insert',
    'workspace_item_overrides.overrides_delete_org',
    'workspace_item_overrides.overrides_insert_org',
    'workspace_item_overrides.overrides_update_org',
    'workspace_settings.settings_update_admin',
    'workspace_settings.settings_write_admin',
    'workspace_tags.workspace_tags_org_delete',
    'workspace_tags.workspace_tags_org_insert'
  ];
  v_pair text;
  v_row  record;
  v_role text;
BEGIN
  FOREACH v_role IN ARRAY ARRAY['anon', 'authenticated', 'service_role', 'postgres'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = v_role) THEN
      RAISE EXCEPTION 'ABORT: role % does not exist', v_role;
    END IF;
  END LOOP;

  FOREACH v_pair IN ARRAY v_list LOOP
    SELECT p.roles, p.cmd, coalesce(p.qual, '') || ' ' || coalesce(p.with_check, '') AS pred
      INTO v_row
      FROM pg_policies p
     WHERE p.schemaname = 'public'
       AND p.tablename = split_part(v_pair, '.', 1)
       AND p.policyname = split_part(v_pair, '.', 2);
    IF NOT FOUND THEN
      RAISE EXCEPTION 'ABORT: policy % on public.% does not exist', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1);
    END IF;
    IF v_row.cmd NOT IN ('INSERT', 'UPDATE', 'DELETE', 'ALL') THEN
      RAISE EXCEPTION 'ABORT: policy % on public.% is a % policy, not a write policy', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1), v_row.cmd;
    END IF;
    IF NOT (v_row.roles @> ARRAY['public']::name[] AND v_row.roles <@ ARRAY['public']::name[])
       AND NOT (v_row.roles @> ARRAY['authenticated', 'service_role']::name[] AND v_row.roles <@ ARRAY['authenticated', 'service_role']::name[]) THEN
      RAISE EXCEPTION 'ABORT: policy % on public.% has roles %, expected {public} (or already {authenticated,service_role}); the live policy changed since this file was written', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1), v_row.roles;
    END IF;
    IF NOT pg_temp.sec7_requires_auth(v_row.pred) THEN
      RAISE EXCEPTION 'ABORT: policy % on public.% does not name an authenticated actor in its live predicate; narrowing its roles could change what anon may do', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1);
    END IF;
  END LOOP;
END $pre$;

-- ---- Part 1: the explicit list ------------------------------------------------------------------------------------
-- admin_action_cooldowns
ALTER POLICY "service role full access" ON public.admin_action_cooldowns TO authenticated, service_role;
-- canonical_source_candidates
ALTER POLICY canonical_source_candidates_admin_write ON public.canonical_source_candidates TO authenticated, service_role;
-- community_group_invitations
ALTER POLICY community_group_invitations_insert_admin ON public.community_group_invitations TO authenticated, service_role;
ALTER POLICY community_group_invitations_service_role ON public.community_group_invitations TO authenticated, service_role;
ALTER POLICY community_group_invitations_update_admin ON public.community_group_invitations TO authenticated, service_role;
ALTER POLICY community_group_invitations_update_invitee ON public.community_group_invitations TO authenticated, service_role;
-- community_group_members
ALTER POLICY community_group_members_delete_self_or_admin ON public.community_group_members TO authenticated, service_role;
ALTER POLICY community_group_members_insert_admin ON public.community_group_members TO authenticated, service_role;
ALTER POLICY community_group_members_service_role ON public.community_group_members TO authenticated, service_role;
ALTER POLICY community_group_members_update_self_prefs ON public.community_group_members TO authenticated, service_role;
-- community_groups
ALTER POLICY community_groups_delete_owner_or_admin ON public.community_groups TO authenticated, service_role;
ALTER POLICY community_groups_insert_authenticated ON public.community_groups TO authenticated, service_role;
ALTER POLICY community_groups_service_role ON public.community_groups TO authenticated, service_role;
ALTER POLICY community_groups_update_owner_or_admin ON public.community_groups TO authenticated, service_role;
-- community_member_profiles
ALTER POLICY community_member_profiles_service_role ON public.community_member_profiles TO authenticated, service_role;
ALTER POLICY community_member_profiles_update_own ON public.community_member_profiles TO authenticated, service_role;
ALTER POLICY community_member_profiles_upsert_own ON public.community_member_profiles TO authenticated, service_role;
-- community_post_signoff_requests
ALTER POLICY signoff_decide ON public.community_post_signoff_requests TO authenticated, service_role;
ALTER POLICY signoff_insert ON public.community_post_signoff_requests TO authenticated, service_role;
ALTER POLICY signoff_withdraw_own ON public.community_post_signoff_requests TO authenticated, service_role;
-- community_posts
ALTER POLICY community_posts_delete_author_or_admin ON public.community_posts TO authenticated, service_role;
ALTER POLICY community_posts_insert_member ON public.community_posts TO authenticated, service_role;
ALTER POLICY community_posts_service_role ON public.community_posts TO authenticated, service_role;
ALTER POLICY community_posts_update_author_or_admin ON public.community_posts TO authenticated, service_role;
-- community_thread_entities
ALTER POLICY community_thread_entities_insert_author ON public.community_thread_entities TO authenticated, service_role;
ALTER POLICY community_thread_entities_service_role ON public.community_thread_entities TO authenticated, service_role;
-- community_topic_groups
ALTER POLICY community_topic_groups_delete_owner ON public.community_topic_groups TO authenticated, service_role;
ALTER POLICY community_topic_groups_insert_owner ON public.community_topic_groups TO authenticated, service_role;
ALTER POLICY community_topic_groups_service_role ON public.community_topic_groups TO authenticated, service_role;
-- community_topics
ALTER POLICY community_topics_delete_owner ON public.community_topics TO authenticated, service_role;
ALTER POLICY community_topics_insert_owner ON public.community_topics TO authenticated, service_role;
ALTER POLICY community_topics_service_role ON public.community_topics TO authenticated, service_role;
ALTER POLICY community_topics_update_owner ON public.community_topics TO authenticated, service_role;
-- connection_theme_runs
ALTER POLICY connection_theme_runs_admin_write ON public.connection_theme_runs TO authenticated, service_role;
-- connection_themes
ALTER POLICY connection_themes_admin_write ON public.connection_themes TO authenticated, service_role;
-- holdings_quality
ALTER POLICY holdings_quality_service_role_write ON public.holdings_quality TO authenticated, service_role;
-- ingest_rejections
ALTER POLICY ingest_rejections_update_platform_admin ON public.ingest_rejections TO authenticated, service_role;
-- integrity_flags
ALTER POLICY integrity_flags_admin_update ON public.integrity_flags TO authenticated, service_role;
ALTER POLICY integrity_flags_service_role_write ON public.integrity_flags TO authenticated, service_role;
-- intelligence_items
ALTER POLICY intelligence_items_admin_delete ON public.intelligence_items TO authenticated, service_role;
ALTER POLICY intelligence_items_admin_insert ON public.intelligence_items TO authenticated, service_role;
ALTER POLICY intelligence_items_admin_update ON public.intelligence_items TO authenticated, service_role;
-- item_assignments
ALTER POLICY item_assignments_delete_party ON public.item_assignments TO authenticated, service_role;
ALTER POLICY item_assignments_insert_member ON public.item_assignments TO authenticated, service_role;
ALTER POLICY item_assignments_update_party ON public.item_assignments TO authenticated, service_role;
-- item_changelog
ALTER POLICY item_changelog_admin_write ON public.item_changelog TO authenticated, service_role;
-- item_cross_references
ALTER POLICY item_cross_references_admin_delete ON public.item_cross_references TO authenticated, service_role;
ALTER POLICY item_cross_references_admin_write ON public.item_cross_references TO authenticated, service_role;
-- item_disputes
ALTER POLICY item_disputes_admin_update ON public.item_disputes TO authenticated, service_role;
ALTER POLICY item_disputes_admin_write ON public.item_disputes TO authenticated, service_role;
-- item_notes
ALTER POLICY item_notes_insert_member ON public.item_notes TO authenticated, service_role;
ALTER POLICY item_notes_update_author_or_admin ON public.item_notes TO authenticated, service_role;
-- item_supersessions
ALTER POLICY item_supersessions_admin_write ON public.item_supersessions TO authenticated, service_role;
-- item_timelines
ALTER POLICY item_timelines_admin_update ON public.item_timelines TO authenticated, service_role;
ALTER POLICY item_timelines_admin_write ON public.item_timelines TO authenticated, service_role;
-- item_workspace_tags
ALTER POLICY item_workspace_tags_org_delete ON public.item_workspace_tags TO authenticated, service_role;
ALTER POLICY item_workspace_tags_org_insert ON public.item_workspace_tags TO authenticated, service_role;
-- moderation_reports
ALTER POLICY moderation_reports_insert_authenticated ON public.moderation_reports TO authenticated, service_role;
ALTER POLICY moderation_reports_service_role ON public.moderation_reports TO authenticated, service_role;
ALTER POLICY moderation_reports_update_admin ON public.moderation_reports TO authenticated, service_role;
-- monitoring_queue
ALTER POLICY monitoring_queue_admin_update ON public.monitoring_queue TO authenticated, service_role;
ALTER POLICY monitoring_queue_admin_write ON public.monitoring_queue TO authenticated, service_role;
-- notification_preferences
ALTER POLICY notification_preferences_delete_self ON public.notification_preferences TO authenticated, service_role;
ALTER POLICY notification_preferences_insert_self ON public.notification_preferences TO authenticated, service_role;
ALTER POLICY notification_preferences_service_role ON public.notification_preferences TO authenticated, service_role;
ALTER POLICY notification_preferences_update_self ON public.notification_preferences TO authenticated, service_role;
-- notifications
ALTER POLICY notifications_service_role ON public.notifications TO authenticated, service_role;
ALTER POLICY notifications_update_self_read ON public.notifications TO authenticated, service_role;
-- org_invitations
ALTER POLICY org_invitations_admin_insert ON public.org_invitations TO authenticated, service_role;
ALTER POLICY org_invitations_admin_update ON public.org_invitations TO authenticated, service_role;
ALTER POLICY org_invitations_service_role ON public.org_invitations TO authenticated, service_role;
-- org_memberships
ALTER POLICY membership_delete_admin ON public.org_memberships TO authenticated, service_role;
ALTER POLICY membership_update_admin ON public.org_memberships TO authenticated, service_role;
ALTER POLICY membership_write_admin ON public.org_memberships TO authenticated, service_role;
-- org_watchlist
ALTER POLICY org_watchlist_member_delete ON public.org_watchlist TO authenticated, service_role;
ALTER POLICY org_watchlist_member_insert ON public.org_watchlist TO authenticated, service_role;
ALTER POLICY org_watchlist_member_update ON public.org_watchlist TO authenticated, service_role;
-- organizations
ALTER POLICY org_update_admin ON public.organizations TO authenticated, service_role;
ALTER POLICY org_write_service ON public.organizations TO authenticated, service_role;
-- pending_jurisdiction_review
ALTER POLICY pjr_update_platform_admin ON public.pending_jurisdiction_review TO authenticated, service_role;
-- portfolio_members
ALTER POLICY portfolio_members_org_delete ON public.portfolio_members TO authenticated, service_role;
ALTER POLICY portfolio_members_org_insert ON public.portfolio_members TO authenticated, service_role;
-- portfolios
ALTER POLICY portfolios_org_delete ON public.portfolios TO authenticated, service_role;
ALTER POLICY portfolios_org_insert ON public.portfolios TO authenticated, service_role;
ALTER POLICY portfolios_org_update ON public.portfolios TO authenticated, service_role;
-- provisional_sources
ALTER POLICY provisional_sources_admin_update ON public.provisional_sources TO authenticated, service_role;
ALTER POLICY provisional_sources_admin_write ON public.provisional_sources TO authenticated, service_role;
-- source_citations
ALTER POLICY source_citations_admin_write ON public.source_citations TO authenticated, service_role;
-- source_tier_opinions
ALTER POLICY source_tier_opinions_update_platform_admin ON public.source_tier_opinions TO authenticated, service_role;
-- source_trust_events
ALTER POLICY source_trust_events_admin_insert ON public.source_trust_events TO authenticated, service_role;
-- sources
ALTER POLICY sources_admin_delete ON public.sources TO authenticated, service_role;
ALTER POLICY sources_admin_insert ON public.sources TO authenticated, service_role;
ALTER POLICY sources_admin_update ON public.sources TO authenticated, service_role;
-- staged_updates
ALTER POLICY staged_updates_admin_update ON public.staged_updates TO authenticated, service_role;
ALTER POLICY staged_updates_admin_write ON public.staged_updates TO authenticated, service_role;
-- user_item_state
ALTER POLICY user_item_state_delete ON public.user_item_state TO authenticated, service_role;
ALTER POLICY user_item_state_insert ON public.user_item_state TO authenticated, service_role;
ALTER POLICY user_item_state_update ON public.user_item_state TO authenticated, service_role;
-- user_watchlist
ALTER POLICY user_watchlist_delete ON public.user_watchlist TO authenticated, service_role;
ALTER POLICY user_watchlist_insert ON public.user_watchlist TO authenticated, service_role;
-- workspace_item_overrides
ALTER POLICY overrides_delete_org ON public.workspace_item_overrides TO authenticated, service_role;
ALTER POLICY overrides_insert_org ON public.workspace_item_overrides TO authenticated, service_role;
ALTER POLICY overrides_update_org ON public.workspace_item_overrides TO authenticated, service_role;
-- workspace_settings
ALTER POLICY settings_update_admin ON public.workspace_settings TO authenticated, service_role;
ALTER POLICY settings_write_admin ON public.workspace_settings TO authenticated, service_role;
-- workspace_tags
ALTER POLICY workspace_tags_org_delete ON public.workspace_tags TO authenticated, service_role;
ALTER POLICY workspace_tags_org_insert ON public.workspace_tags TO authenticated, service_role;

-- ---- Part 2: out-of-band write policies (live only, recorded by no migration file) ------------------------------------
DO $oob$
DECLARE
  v_pair text;
  v_row  record;
  v_n    integer := 0;
BEGIN
  FOREACH v_pair IN ARRAY ARRAY[
    'intelligence_summaries.summaries_write_service',
    'intelligence_summaries.summaries_update_service',
    'intelligence_changes.changes_write_service',
    'sector_contexts.sector_contexts_write_service'
  ] LOOP
    SELECT p.roles, p.cmd, coalesce(p.qual, '') || ' ' || coalesce(p.with_check, '') AS pred
      INTO v_row
      FROM pg_policies p
     WHERE p.schemaname = 'public'
       AND p.tablename = split_part(v_pair, '.', 1)
       AND p.policyname = split_part(v_pair, '.', 2);
    IF NOT FOUND THEN
      RAISE NOTICE 'migration 381: out-of-band policy % on public.% does not exist on this database, skipped', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1);
      CONTINUE;
    END IF;
    IF v_row.cmd NOT IN ('INSERT', 'UPDATE', 'DELETE', 'ALL') THEN
      RAISE EXCEPTION 'ABORT: out-of-band policy % on public.% is a % policy, not a write policy', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1), v_row.cmd;
    END IF;
    IF v_row.roles @> ARRAY['authenticated', 'service_role']::name[] AND v_row.roles <@ ARRAY['authenticated', 'service_role']::name[] THEN
      CONTINUE;
    END IF;
    IF NOT (v_row.roles @> ARRAY['public']::name[] AND v_row.roles <@ ARRAY['public']::name[]) THEN
      RAISE EXCEPTION 'ABORT: out-of-band policy % on public.% has roles %, expected {public}', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1), v_row.roles;
    END IF;
    IF NOT pg_temp.sec7_requires_auth(v_row.pred) THEN
      RAISE EXCEPTION 'ABORT: out-of-band policy % on public.% does not name an authenticated actor in its live predicate (%); anon could satisfy it', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1), v_row.pred;
    END IF;
    EXECUTE format('ALTER POLICY %I ON public.%I TO authenticated, service_role', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1));
    v_n := v_n + 1;
  END LOOP;
  RAISE NOTICE 'migration 381: % out-of-band write policy(ies) narrowed to authenticated, service_role', v_n;
END $oob$;

-- ---- Part 3: the enumeration as assertion ---------------------------------------------------------------------------
DO $enum$
DECLARE
  v_missed text;
BEGIN
  SELECT string_agg(p.tablename || '.' || p.policyname, ', ' ORDER BY p.tablename, p.policyname) INTO v_missed
    FROM pg_policies p
   WHERE p.schemaname = 'public'
     AND p.cmd IN ('INSERT', 'UPDATE', 'DELETE', 'ALL')
     AND p.roles @> ARRAY['public']::name[] AND p.roles <@ ARRAY['public']::name[]
     AND NOT EXISTS (
       SELECT 1 FROM pg_policies q
        WHERE q.schemaname = 'public' AND q.tablename = p.tablename
          AND q.cmd IN ('INSERT', 'UPDATE', 'DELETE', 'ALL')
          AND q.roles && ARRAY['anon', 'public']::name[]
          AND NOT pg_temp.sec7_requires_auth(coalesce(q.qual, '') || ' ' || coalesce(q.with_check, ''))
     );
  IF v_missed IS NOT NULL THEN
    RAISE EXCEPTION 'ABORT: write policies with roles {public} on tables whose write policies all require an authenticated actor remain after the ALTERs (add them to the explicit list): %', v_missed;
  END IF;
END $enum$;

-- ---- Part 4: grant hygiene again (migration 369 section 3, verbatim statements; anon: the six, authenticated: three) ----
DO $$
DECLARE
  r record;
  v_anon oid := (SELECT oid FROM pg_roles WHERE rolname = 'anon');
  v_auth oid := (SELECT oid FROM pg_roles WHERE rolname = 'authenticated');
  v_sel_before integer;
  v_sel_after integer;
  v_iud_before integer;
  v_iud_after integer;
  v_regranted integer := 0;
  v_list text := '';
BEGIN
  SELECT count(*) INTO v_sel_before
    FROM pg_class c, aclexplode(c.relacl) a
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p', 'v')
     AND a.grantee = v_anon AND a.privilege_type = 'SELECT';
  SELECT count(*) INTO v_iud_before
    FROM pg_class c, aclexplode(c.relacl) a
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p')
     AND a.grantee = v_auth AND a.privilege_type IN ('INSERT', 'UPDATE', 'DELETE');

  REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public FROM anon;
  REVOKE TRUNCATE, TRIGGER, REFERENCES ON ALL TABLES IN SCHEMA public FROM authenticated;

  FOR r IN
    SELECT p.tablename AS t,
           bool_or(p.cmd IN ('INSERT', 'ALL')) AS ins,
           bool_or(p.cmd IN ('UPDATE', 'ALL')) AS upd,
           bool_or(p.cmd IN ('DELETE', 'ALL')) AS del
      FROM pg_policies p
      JOIN pg_class c ON c.relname = p.tablename AND c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p')
     WHERE p.schemaname = 'public'
       AND p.roles && ARRAY['anon', 'public']::name[]
       AND p.cmd IN ('INSERT', 'UPDATE', 'DELETE', 'ALL')
     GROUP BY p.tablename
     ORDER BY p.tablename
  LOOP
    IF r.ins THEN EXECUTE format('GRANT INSERT ON public.%I TO anon', r.t); END IF;
    IF r.upd THEN EXECUTE format('GRANT UPDATE ON public.%I TO anon', r.t); END IF;
    IF r.del THEN EXECUTE format('GRANT DELETE ON public.%I TO anon', r.t); END IF;
    v_regranted := v_regranted + 1;
    v_list := v_list || CASE WHEN v_list = '' THEN '' ELSE ', ' END || r.t;
  END LOOP;

  SELECT count(*) INTO v_sel_after
    FROM pg_class c, aclexplode(c.relacl) a
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p', 'v')
     AND a.grantee = v_anon AND a.privilege_type = 'SELECT';
  IF v_sel_after <> v_sel_before THEN
    RAISE EXCEPTION 'ABORT: the anon SELECT grant count changed from % to % (this migration must not touch SELECT)', v_sel_before, v_sel_after;
  END IF;
  SELECT count(*) INTO v_iud_after
    FROM pg_class c, aclexplode(c.relacl) a
   WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p')
     AND a.grantee = v_auth AND a.privilege_type IN ('INSERT', 'UPDATE', 'DELETE');
  IF v_iud_after <> v_iud_before THEN
    RAISE EXCEPTION 'ABORT: the authenticated INSERT, UPDATE, DELETE grant count changed from % to % (SEC-3b owns those)', v_iud_before, v_iud_after;
  END IF;

  RAISE NOTICE 'migration 381 (grant hygiene, 369 section 3 repeated): anon write privileges re-granted on % table(s) that carry a write policy naming anon or public: %', v_regranted, coalesce(nullif(v_list, ''), '(none)');
END $$;

-- ---- Self-check: attack every touched table as anon, prove the real principals unchanged, rolled back ---------------
-- sec7_try runs one statement as anon, authenticated (with a fixture JWT subject) or service_role and returns
-- 'ok:<rows>' or 'err:<sqlstate>:<first line of the message>'; sec7_expect raises ABORT when the result does not match.
CREATE FUNCTION pg_temp.sec7_try(p_role text, p_uid uuid, p_sql text)
RETURNS text
LANGUAGE plpgsql
AS $f$
DECLARE
  v_rows integer;
BEGIN
  IF p_role = 'service_role' THEN
    SET LOCAL ROLE service_role;
  ELSIF p_role = 'anon' THEN
    SET LOCAL ROLE anon;
  ELSE
    SET LOCAL ROLE authenticated;
  END IF;
  PERFORM set_config('request.jwt.claims',
    json_build_object('sub', p_uid::text, 'role', p_role)::text, true);
  PERFORM set_config('request.jwt.claim.sub', coalesce(p_uid::text, ''), true);
  PERFORM set_config('request.jwt.claim.role', p_role, true);
  BEGIN
    EXECUTE p_sql;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    RESET ROLE;
    RETURN 'ok:' || v_rows::text;
  EXCEPTION WHEN OTHERS THEN
    RESET ROLE;
    RETURN 'err:' || SQLSTATE || ':' || split_part(SQLERRM, E'\n', 1);
  END;
END;
$f$;

CREATE FUNCTION pg_temp.sec7_expect(p_label text, p_got text, p_want_like text, p_reject_like text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
AS $f$
BEGIN
  IF p_got NOT LIKE p_want_like OR (p_reject_like IS NOT NULL AND p_got LIKE p_reject_like) THEN
    RAISE EXCEPTION 'ABORT: % expected % but got %', p_label, p_want_like, p_got;
  END IF;
END;
$f$;

DO $sc$
DECLARE
  v_tables text[] := ARRAY[
    'admin_action_cooldowns',
    'canonical_source_candidates',
    'community_group_invitations',
    'community_group_members',
    'community_groups',
    'community_member_profiles',
    'community_post_signoff_requests',
    'community_posts',
    'community_thread_entities',
    'community_topic_groups',
    'community_topics',
    'connection_theme_runs',
    'connection_themes',
    'holdings_quality',
    'ingest_rejections',
    'integrity_flags',
    'intelligence_changes',
    'intelligence_items',
    'intelligence_summaries',
    'item_assignments',
    'item_changelog',
    'item_cross_references',
    'item_disputes',
    'item_notes',
    'item_supersessions',
    'item_timelines',
    'item_workspace_tags',
    'moderation_reports',
    'monitoring_queue',
    'notification_preferences',
    'notifications',
    'org_invitations',
    'org_memberships',
    'org_watchlist',
    'organizations',
    'pending_jurisdiction_review',
    'portfolio_members',
    'portfolios',
    'provisional_sources',
    'sector_contexts',
    'source_citations',
    'source_tier_opinions',
    'source_trust_events',
    'sources',
    'staged_updates',
    'user_item_state',
    'user_watchlist',
    'workspace_item_overrides',
    'workspace_settings',
    'workspace_tags'
  ];
  v_pols   text[] := ARRAY[
    'admin_action_cooldowns.service role full access',
    'canonical_source_candidates.canonical_source_candidates_admin_write',
    'community_group_invitations.community_group_invitations_insert_admin',
    'community_group_invitations.community_group_invitations_service_role',
    'community_group_invitations.community_group_invitations_update_admin',
    'community_group_invitations.community_group_invitations_update_invitee',
    'community_group_members.community_group_members_delete_self_or_admin',
    'community_group_members.community_group_members_insert_admin',
    'community_group_members.community_group_members_service_role',
    'community_group_members.community_group_members_update_self_prefs',
    'community_groups.community_groups_delete_owner_or_admin',
    'community_groups.community_groups_insert_authenticated',
    'community_groups.community_groups_service_role',
    'community_groups.community_groups_update_owner_or_admin',
    'community_member_profiles.community_member_profiles_service_role',
    'community_member_profiles.community_member_profiles_update_own',
    'community_member_profiles.community_member_profiles_upsert_own',
    'community_post_signoff_requests.signoff_decide',
    'community_post_signoff_requests.signoff_insert',
    'community_post_signoff_requests.signoff_withdraw_own',
    'community_posts.community_posts_delete_author_or_admin',
    'community_posts.community_posts_insert_member',
    'community_posts.community_posts_service_role',
    'community_posts.community_posts_update_author_or_admin',
    'community_thread_entities.community_thread_entities_insert_author',
    'community_thread_entities.community_thread_entities_service_role',
    'community_topic_groups.community_topic_groups_delete_owner',
    'community_topic_groups.community_topic_groups_insert_owner',
    'community_topic_groups.community_topic_groups_service_role',
    'community_topics.community_topics_delete_owner',
    'community_topics.community_topics_insert_owner',
    'community_topics.community_topics_service_role',
    'community_topics.community_topics_update_owner',
    'connection_theme_runs.connection_theme_runs_admin_write',
    'connection_themes.connection_themes_admin_write',
    'holdings_quality.holdings_quality_service_role_write',
    'ingest_rejections.ingest_rejections_update_platform_admin',
    'integrity_flags.integrity_flags_admin_update',
    'integrity_flags.integrity_flags_service_role_write',
    'intelligence_items.intelligence_items_admin_delete',
    'intelligence_items.intelligence_items_admin_insert',
    'intelligence_items.intelligence_items_admin_update',
    'item_assignments.item_assignments_delete_party',
    'item_assignments.item_assignments_insert_member',
    'item_assignments.item_assignments_update_party',
    'item_changelog.item_changelog_admin_write',
    'item_cross_references.item_cross_references_admin_delete',
    'item_cross_references.item_cross_references_admin_write',
    'item_disputes.item_disputes_admin_update',
    'item_disputes.item_disputes_admin_write',
    'item_notes.item_notes_insert_member',
    'item_notes.item_notes_update_author_or_admin',
    'item_supersessions.item_supersessions_admin_write',
    'item_timelines.item_timelines_admin_update',
    'item_timelines.item_timelines_admin_write',
    'item_workspace_tags.item_workspace_tags_org_delete',
    'item_workspace_tags.item_workspace_tags_org_insert',
    'moderation_reports.moderation_reports_insert_authenticated',
    'moderation_reports.moderation_reports_service_role',
    'moderation_reports.moderation_reports_update_admin',
    'monitoring_queue.monitoring_queue_admin_update',
    'monitoring_queue.monitoring_queue_admin_write',
    'notification_preferences.notification_preferences_delete_self',
    'notification_preferences.notification_preferences_insert_self',
    'notification_preferences.notification_preferences_service_role',
    'notification_preferences.notification_preferences_update_self',
    'notifications.notifications_service_role',
    'notifications.notifications_update_self_read',
    'org_invitations.org_invitations_admin_insert',
    'org_invitations.org_invitations_admin_update',
    'org_invitations.org_invitations_service_role',
    'org_memberships.membership_delete_admin',
    'org_memberships.membership_update_admin',
    'org_memberships.membership_write_admin',
    'org_watchlist.org_watchlist_member_delete',
    'org_watchlist.org_watchlist_member_insert',
    'org_watchlist.org_watchlist_member_update',
    'organizations.org_update_admin',
    'organizations.org_write_service',
    'pending_jurisdiction_review.pjr_update_platform_admin',
    'portfolio_members.portfolio_members_org_delete',
    'portfolio_members.portfolio_members_org_insert',
    'portfolios.portfolios_org_delete',
    'portfolios.portfolios_org_insert',
    'portfolios.portfolios_org_update',
    'provisional_sources.provisional_sources_admin_update',
    'provisional_sources.provisional_sources_admin_write',
    'source_citations.source_citations_admin_write',
    'source_tier_opinions.source_tier_opinions_update_platform_admin',
    'source_trust_events.source_trust_events_admin_insert',
    'sources.sources_admin_delete',
    'sources.sources_admin_insert',
    'sources.sources_admin_update',
    'staged_updates.staged_updates_admin_update',
    'staged_updates.staged_updates_admin_write',
    'user_item_state.user_item_state_delete',
    'user_item_state.user_item_state_insert',
    'user_item_state.user_item_state_update',
    'user_watchlist.user_watchlist_delete',
    'user_watchlist.user_watchlist_insert',
    'workspace_item_overrides.overrides_delete_org',
    'workspace_item_overrides.overrides_insert_org',
    'workspace_item_overrides.overrides_update_org',
    'workspace_settings.settings_update_admin',
    'workspace_settings.settings_write_admin',
    'workspace_tags.workspace_tags_org_delete',
    'workspace_tags.workspace_tags_org_insert'
  ];
  v_tbl    text;
  v_oid    oid;
  v_col    text;
  v_priv   text;
  v_cmd    text;
  v_bad    text;
  v_kept   text := '';
  v_pair   text;
  v_ok     boolean := true;
  v_owner  uuid := gen_random_uuid();
  v_member uuid := gen_random_uuid();
  v_viewer uuid := gen_random_uuid();
  v_extra  uuid := gen_random_uuid();
  v_users  uuid[];
  v_u      uuid;
  v_org    uuid;
  v_grp    uuid;
  v_pf     uuid;
BEGIN
  BEGIN
    -- ======== A. the catalog ========
    -- A1. every listed policy now names exactly authenticated and service_role.
    FOREACH v_pair IN ARRAY v_pols LOOP
      IF NOT EXISTS (
        SELECT 1 FROM pg_policies p
         WHERE p.schemaname = 'public' AND p.tablename = split_part(v_pair, '.', 1) AND p.policyname = split_part(v_pair, '.', 2)
           AND p.roles @> ARRAY['authenticated', 'service_role']::name[] AND p.roles <@ ARRAY['authenticated', 'service_role']::name[]
      ) THEN
        RAISE EXCEPTION 'ABORT: policy % on public.% does not carry roles {authenticated,service_role} after the ALTERs', split_part(v_pair, '.', 2), split_part(v_pair, '.', 1);
      END IF;
    END LOOP;

    -- A2. no write policy with roles {public} remains on a table whose write policies all require an authenticated actor
    -- (the same enumeration as part 3, re-read after the grant block).
    SELECT string_agg(p.tablename || '.' || p.policyname, ', ') INTO v_bad
      FROM pg_policies p
     WHERE p.schemaname = 'public' AND p.cmd IN ('INSERT', 'UPDATE', 'DELETE', 'ALL')
       AND p.roles @> ARRAY['public']::name[] AND p.roles <@ ARRAY['public']::name[]
       AND NOT EXISTS (
         SELECT 1 FROM pg_policies q
          WHERE q.schemaname = 'public' AND q.tablename = p.tablename AND q.cmd IN ('INSERT', 'UPDATE', 'DELETE', 'ALL')
            AND q.roles && ARRAY['anon', 'public']::name[]
            AND NOT pg_temp.sec7_requires_auth(coalesce(q.qual, '') || ' ' || coalesce(q.with_check, '')));
    IF v_bad IS NOT NULL THEN
      RAISE EXCEPTION 'ABORT: write policies with roles {public} on auth-only tables remain: %', v_bad;
    END IF;

    -- A3. anon holds no INSERT, UPDATE or DELETE (table level or any column) on a public table unless a policy that applies
    -- to anon or public for that command justifies it; the tables that keep one are named.
    FOR v_oid, v_tbl IN
      SELECT c.oid, c.relname FROM pg_class c WHERE c.relnamespace = 'public'::regnamespace AND c.relkind IN ('r', 'p') ORDER BY c.relname
    LOOP
      FOREACH v_priv IN ARRAY ARRAY['INSERT', 'UPDATE', 'DELETE'] LOOP
        IF (CASE WHEN v_priv = 'DELETE' THEN has_table_privilege('anon', v_oid, v_priv) ELSE has_any_column_privilege('anon', v_oid, v_priv) END) THEN
          IF NOT EXISTS (
            SELECT 1 FROM pg_policies p
             WHERE p.schemaname = 'public' AND p.tablename = v_tbl AND p.roles && ARRAY['anon', 'public']::name[]
               AND (p.cmd = v_priv OR p.cmd = 'ALL')
          ) THEN
            RAISE EXCEPTION 'ABORT: anon holds % on public.% with no policy that applies to anon or public for it', v_priv, v_tbl;
          END IF;
          v_kept := v_kept || CASE WHEN v_kept = '' THEN '' ELSE ', ' END || v_tbl || ':' || v_priv;
        END IF;
      END LOOP;
    END LOOP;
    RAISE NOTICE 'migration 381 self-check: anon keeps a write privilege that an anon-or-public policy justifies on: %', coalesce(nullif(v_kept, ''), '(none)');

    -- ======== B. every touched table, anon, all three commands: refused on the GRANT ========
    FOREACH v_tbl IN ARRAY v_tables LOOP
      v_oid := to_regclass('public.' || quote_ident(v_tbl));
      IF v_oid IS NULL THEN
        RAISE NOTICE 'migration 381 self-check: public.% does not exist on this database, skipped', v_tbl;
        CONTINUE;
      END IF;
      SELECT a.attname INTO v_col FROM pg_attribute a
       WHERE a.attrelid = v_oid AND a.attnum > 0 AND NOT a.attisdropped AND a.attgenerated = '' AND a.attidentity = ''
       ORDER BY a.attnum LIMIT 1;
      FOREACH v_cmd IN ARRAY ARRAY['INSERT', 'UPDATE', 'DELETE'] LOOP
        IF (CASE WHEN v_cmd = 'DELETE' THEN has_table_privilege('anon', v_oid, v_cmd) ELSE has_any_column_privilege('anon', v_oid, v_cmd) END) THEN
          RAISE NOTICE 'migration 381 self-check: anon keeps % on public.% (a policy that applies to anon justifies it), attack skipped', v_cmd, v_tbl;
          CONTINUE;
        END IF;
        PERFORM pg_temp.sec7_expect('B anon ' || v_cmd || ' on ' || v_tbl,
          pg_temp.sec7_try('anon', NULL,
            CASE v_cmd
              WHEN 'INSERT' THEN format('INSERT INTO public.%I DEFAULT VALUES', v_tbl)
              WHEN 'UPDATE' THEN format('UPDATE public.%I SET %I = %I WHERE false', v_tbl, v_col, v_col)
              ELSE format('DELETE FROM public.%I WHERE false', v_tbl)
            END),
          'err:42501:permission denied for table %');
      END LOOP;
    END LOOP;

    -- ======== C. fixtures: the cells AT1 found refused on a helper function, and the real principals ========
    v_users := ARRAY[v_owner, v_member, v_viewer, v_extra];
    BEGIN
      FOREACH v_u IN ARRAY v_users LOOP
        INSERT INTO auth.users (id, aud, role, email, created_at, updated_at)
        VALUES (v_u, 'authenticated', 'authenticated', 'sec7-' || v_u::text || '@sec7-selfcheck.invalid', now(), now());
        INSERT INTO public.profiles (id, email, display_name)
        VALUES (v_u, 'sec7-' || v_u::text || '@sec7-selfcheck.invalid', 'sec7 selfcheck')
        ON CONFLICT (id) DO NOTHING;
      END LOOP;
    EXCEPTION WHEN OTHERS THEN
      v_ok := false;
      RAISE NOTICE 'migration 381 self-check: could not create fixture auth.users and profiles rows (%), fixture legs skipped; catalog and per-table attack legs still ran', SQLERRM;
    END;

    IF v_ok THEN
      INSERT INTO public.organizations (name, slug) VALUES ('sec7 selfcheck', 'sec7-' || v_owner::text) RETURNING id INTO v_org;
      INSERT INTO public.org_memberships (org_id, user_id, role) VALUES
        (v_org, v_owner, 'owner'), (v_org, v_member, 'member'), (v_org, v_viewer, 'viewer');
      INSERT INTO public.community_groups (name, slug, region, privacy, owner_user_id)
      VALUES ('sec7 g', 'sec7-g-' || v_owner::text, 'EU', 'public', v_owner) RETURNING id INTO v_grp;
      INSERT INTO public.community_group_members (group_id, user_id, role) VALUES (v_grp, v_owner, 'admin');

      -- C1. org_watchlist (user_can_write_in_org family): anon refused on the grant, not on the helper
      PERFORM pg_temp.sec7_expect('C1 anon INSERT org_watchlist with a valid row is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('INSERT INTO public.org_watchlist (org_id, added_by_user_id, item_type, item_id) VALUES (%L, %L, %L, %L)', v_org, v_member, 'reg', 'sec7-anon')),
        'err:42501:permission denied for table org_watchlist', 'err:42501:permission denied for function%');
      PERFORM pg_temp.sec7_expect('C1 control: an org member inserts a team watchlist row',
        pg_temp.sec7_try('authenticated', v_member, format('INSERT INTO public.org_watchlist (org_id, added_by_user_id, item_type, item_id) VALUES (%L, %L, %L, %L)', v_org, v_member, 'reg', 'sec7-member')),
        'ok:1');
      PERFORM pg_temp.sec7_expect('C1 a viewer is still refused, by the policy and not by the grant',
        pg_temp.sec7_try('authenticated', v_viewer, format('INSERT INTO public.org_watchlist (org_id, added_by_user_id, item_type, item_id) VALUES (%L, %L, %L, %L)', v_org, v_viewer, 'reg', 'sec7-viewer')),
        'err:42501:new row violates row-level security%');
      PERFORM pg_temp.sec7_expect('C1 anon UPDATE org_watchlist with a real row is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('UPDATE public.org_watchlist SET note = %L WHERE org_id = %L', 'sec7', v_org)),
        'err:42501:permission denied for table org_watchlist');
      PERFORM pg_temp.sec7_expect('C1 anon DELETE org_watchlist with a real row is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('DELETE FROM public.org_watchlist WHERE org_id = %L', v_org)),
        'err:42501:permission denied for table org_watchlist');
      PERFORM pg_temp.sec7_expect('C1 control: an org member updates a team watchlist row',
        pg_temp.sec7_try('authenticated', v_member, format('UPDATE public.org_watchlist SET note = %L WHERE org_id = %L', 'sec7', v_org)),
        'ok:1');
      PERFORM pg_temp.sec7_expect('C1 control: the service role updates a team watchlist row',
        pg_temp.sec7_try('service_role', NULL, format('UPDATE public.org_watchlist SET note = %L WHERE org_id = %L', 'sec7 service', v_org)),
        'ok:1');

      -- C2. workspace_tags and portfolios (same family)
      PERFORM pg_temp.sec7_expect('C2 anon INSERT workspace_tags is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('INSERT INTO public.workspace_tags (org_id, name, created_by) VALUES (%L, %L, %L)', v_org, 'sec7 anon tag', v_member)),
        'err:42501:permission denied for table workspace_tags', 'err:42501:permission denied for function%');
      PERFORM pg_temp.sec7_expect('C2 control: an org member inserts a workspace tag',
        pg_temp.sec7_try('authenticated', v_member, format('INSERT INTO public.workspace_tags (org_id, name, created_by) VALUES (%L, %L, %L)', v_org, 'sec7 member tag', v_member)),
        'ok:1');
      PERFORM pg_temp.sec7_expect('C2 anon INSERT portfolios is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('INSERT INTO public.portfolios (org_id, name, created_by) VALUES (%L, %L, %L)', v_org, 'sec7 anon pf', v_member)),
        'err:42501:permission denied for table portfolios', 'err:42501:permission denied for function%');
      PERFORM pg_temp.sec7_expect('C2 control: an org member inserts a portfolio',
        pg_temp.sec7_try('authenticated', v_member, format('INSERT INTO public.portfolios (org_id, name, created_by) VALUES (%L, %L, %L)', v_org, 'sec7 member pf', v_member)),
        'ok:1');
      SELECT id INTO v_pf FROM public.portfolios WHERE org_id = v_org LIMIT 1;
      PERFORM pg_temp.sec7_expect('C2 anon UPDATE portfolios is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('UPDATE public.portfolios SET name = %L WHERE id = %L', 'sec7 anon rename', v_pf)),
        'err:42501:permission denied for table portfolios');
      PERFORM pg_temp.sec7_expect('C2 control: an org member renames a portfolio',
        pg_temp.sec7_try('authenticated', v_member, format('UPDATE public.portfolios SET name = %L WHERE id = %L', 'sec7 renamed', v_pf)),
        'ok:1');

      -- C3. org_memberships (user_org_role family)
      PERFORM pg_temp.sec7_expect('C3 anon INSERT org_memberships is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('INSERT INTO public.org_memberships (org_id, user_id, role) VALUES (%L, %L, %L)', v_org, v_extra, 'member')),
        'err:42501:permission denied for table org_memberships', 'err:42501:permission denied for function%');
      PERFORM pg_temp.sec7_expect('C3 anon UPDATE org_memberships is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('UPDATE public.org_memberships SET role = role WHERE org_id = %L', v_org)),
        'err:42501:permission denied for table org_memberships');
      PERFORM pg_temp.sec7_expect('C3 anon DELETE org_memberships is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('DELETE FROM public.org_memberships WHERE org_id = %L', v_org)),
        'err:42501:permission denied for table org_memberships');
      PERFORM pg_temp.sec7_expect('C3 control: the org owner adds a member (policy and role guard still admit it)',
        pg_temp.sec7_try('authenticated', v_owner, format('INSERT INTO public.org_memberships (org_id, user_id, role) VALUES (%L, %L, %L)', v_org, v_extra, 'member')),
        'ok:1', 'err:42P17%');
      PERFORM pg_temp.sec7_expect('C3 control: the org owner removes that member',
        pg_temp.sec7_try('authenticated', v_owner, format('DELETE FROM public.org_memberships WHERE org_id = %L AND user_id = %L', v_org, v_extra)),
        'ok:1', 'err:42P17%');

      -- C4. community_group_members (user_group_role family)
      PERFORM pg_temp.sec7_expect('C4 anon INSERT community_group_members is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('INSERT INTO public.community_group_members (group_id, user_id, role) VALUES (%L, %L, %L)', v_grp, v_extra, 'member')),
        'err:42501:permission denied for table community_group_members', 'err:42501:permission denied for function%');
      PERFORM pg_temp.sec7_expect('C4 anon UPDATE community_group_members is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('UPDATE public.community_group_members SET starred = true WHERE group_id = %L', v_grp)),
        'err:42501:permission denied for table community_group_members');
      PERFORM pg_temp.sec7_expect('C4 control: the group admin adds a member',
        pg_temp.sec7_try('authenticated', v_owner, format('INSERT INTO public.community_group_members (group_id, user_id, role) VALUES (%L, %L, %L)', v_grp, v_extra, 'member')),
        'ok:1', 'err:42P17%');
      PERFORM pg_temp.sec7_expect('C4 control: a member updates their own preference',
        pg_temp.sec7_try('authenticated', v_extra, format('UPDATE public.community_group_members SET starred = true WHERE group_id = %L AND user_id = %L', v_grp, v_extra)),
        'ok:1', 'err:42P17%');

      -- C5. user_watchlist (auth.uid() = user_id)
      PERFORM pg_temp.sec7_expect('C5 anon INSERT user_watchlist is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('INSERT INTO public.user_watchlist (user_id, item_type, item_id) VALUES (%L, %L, %L)', v_member, 'reg', 'sec7-anon')),
        'err:42501:permission denied for table user_watchlist');
      PERFORM pg_temp.sec7_expect('C5 anon DELETE user_watchlist is refused by the grant',
        pg_temp.sec7_try('anon', NULL, format('DELETE FROM public.user_watchlist WHERE user_id = %L', v_member)),
        'err:42501:permission denied for table user_watchlist');
      PERFORM pg_temp.sec7_expect('C5 control: a user writes their own watchlist row',
        pg_temp.sec7_try('authenticated', v_member, format('INSERT INTO public.user_watchlist (user_id, item_type, item_id) VALUES (%L, %L, %L)', v_member, 'reg', 'sec7-own')),
        'ok:1');
      PERFORM pg_temp.sec7_expect('C5 a user still cannot write another user watchlist row (the policy, not the grant)',
        pg_temp.sec7_try('authenticated', v_member, format('INSERT INTO public.user_watchlist (user_id, item_type, item_id) VALUES (%L, %L, %L)', v_viewer, 'reg', 'sec7-foreign')),
        'err:42501:new row violates row-level security%');
    END IF;

    RAISE EXCEPTION 'sec7_381_selfcheck_rollback';
  EXCEPTION WHEN raise_exception THEN
    RESET ROLE;
    IF SQLERRM <> 'sec7_381_selfcheck_rollback' THEN RAISE; END IF;
  END;

  RAISE NOTICE 'migration 381 OK: every write policy whose predicate names an authenticated actor now names its roles (authenticated, service_role); anon holds no INSERT, UPDATE or DELETE on a public table unless an anon-or-public policy justifies it, and its refusal on every touched table is the grant (permission denied for table), not a revoked policy helper; members, viewers, group admins, org owners and the service role behave as before';
END $sc$;

DROP FUNCTION pg_temp.sec7_try(text, uuid, text);
DROP FUNCTION pg_temp.sec7_expect(text, text, text, text);
DROP FUNCTION pg_temp.sec7_requires_auth(text);

COMMIT;

-- Rollback (reversible in intent; do not, it re-opens the grants):
--   ALTER POLICY <each listed policy> ON public.<table> TO public;
--   then re-run migration 369 section 3 (the re-grant loop), which grants anon INSERT, UPDATE and DELETE back on every
--   table whose policy applies to public.
