const U = "https://www.smartfreightcentre.org/en/our-programs/emissions-accounting/global-logistics-emissions-council/";
const res = await fetch(U, { headers: { "user-agent": "Mozilla/5.0 (compatible; CarosLedge/1.0)" }, redirect: "follow", signal: AbortSignal.timeout(30000) });
console.log(`PLAIN: status ${res.status} ${res.statusText}  content-type ${res.headers.get("content-type")}`);
const html = await res.text();
const text = html.replace(/<script[^>]*>[\s\S]*?<\/script>/gi,"").replace(/<style[^>]*>[\s\S]*?<\/style>/gi,"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const blocked = /request could not be satisfied|request blocked|access denied|just a moment/i.test(text);
console.log(`textLen ${text.length}  blocked ${blocked}`);
console.log(`head: ${text.slice(0, 320)}`);
const links = [...html.matchAll(/href=["']([^"']+)["']/gi)].map(m=>m[1]).filter(h=>/\.pdf|s3\.amazonaws|documents\/|glec|framework/i.test(h));
console.log(`\ndoc/glec links (${[...new Set(links)].length}):`);
for (const l of [...new Set(links)].slice(0,15)) console.log(`  ${l}`);
