// Entity gate — decides whether a source's first-fetch should MINT an intelligence_item.
// THE PRINCIPLE (source != item): a portal / navigational homepage (the source's own ROOT URL)
// is a SOURCE, not an item. Its actual regulations become items via scan/monitoring of its
// CONTENTS (deep document URLs) — never by minting the homepage as an item. The leak:
// migration-065 + drain-first-fetch mint ONE item per source UNCONDITIONALLY, so every portal
// homepage became a garbage item.
//
// Deterministic pre-gate FIRST (no AI): a root / trivial-landing URL is almost certainly the
// portal homepage — caught without the classifier (and without the classifier's defaulting bug).
// The Haiku entity_verdict is the backstop for genuinely-ambiguous DEEP urls.
//
// HONEST-INCONCLUSIVE (the bug-class, inverted): the classifier's uncertainty must map to
// 'uncertain' -> DO NOT MINT (flag for review), NOT to a confident document type. first-fetch
// line 191 (Haiku unsure -> default item_type "regulation") is a non-answer mapped to a
// substantive POSITIVE — the same shape as fetch-failure -> negative, here failure -> positive.

export const ENTITY = Object.freeze({ DOCUMENT: "document", PORTAL: "portal", UNCERTAIN: "uncertain" });

// Deterministic: is the URL the source's own root / a trivial landing page (portal homepage)?
// Root ("https://host", "/") or a single shallow landing segment (/en, /home, /index.html).
export function urlIsRoot(url) {
  let u;
  try { u = new URL(url); } catch { return false; }
  const segs = u.pathname.split("/").filter(Boolean);
  if (segs.length === 0) return true; // "https://host" or "https://host/"
  if (segs.length === 1 && !u.search &&
      /^(en|en-us|en-gb|fr|de|es|pt|it|home|index(\.[a-z0-9]+)?|default(\.[a-z0-9]+)?|main|portal|start|welcome)$/i.test(segs[0])) {
    return true;
  }
  return false; // a deep path -> a specific document (Haiku refines)
}

// Combine the deterministic pre-gate with the Haiku entity verdict.
// haikuVerdict in {'specific_document','portal','uncertain'} or undefined (absent/failed).
export function entityVerdict({ url, haikuVerdict } = {}) {
  if (urlIsRoot(url)) return ENTITY.PORTAL;            // deterministic: root URL = portal homepage
  if (haikuVerdict === "portal") return ENTITY.PORTAL;
  if (haikuVerdict === "specific_document") return ENTITY.DOCUMENT;
  return ENTITY.UNCERTAIN;                              // unsure/absent -> HONEST-INCONCLUSIVE, do NOT mint
}

// Should first-fetch MINT an item? Only for a confident specific document.
export function shouldMintItem(input) {
  return entityVerdict(input) === ENTITY.DOCUMENT;
}

// ENTRY-4 — error-page / bot-block BODY detector (the fetchOk principle in ingestion, made
// EXPLICIT not classifier-dependent). A 403/CloudFront/Cloudflare/captcha/timeout error BODY
// captured by the fetch is NOT content — minting it is the "error-body-as-item" leak class.
// urlIsRoot catches root-URL portals; a DEEP-URL error body relies on Haiku saying 'uncertain'
// (implicit, unreliable). This rejects the error-body signature OUTRIGHT, deterministically.
const ERROR_SIGNATURES = [
  /the request could not be satisfied/i,           // CloudFront 403
  /generated by cloudfront/i,
  /request blocked/i,
  /\b403\b\s*(error|forbidden)?/i,
  /\bforbidden\b/i,
  /access denied/i,
  /attention required/i,                            // Cloudflare challenge
  /just a moment\b/i,                               // Cloudflare
  /\bare you (a )?(human|robot)\b/i,
  /\bcaptcha\b/i,
  /please (enable|turn on) (javascript|cookies)/i,
  /(temporarily )?(unavailable|inaccessible)\b/i,
  /service unavailable/i,
  /too many requests/i,
  /\b429\b/,
  /\b50[0234]\b\s*(error|bad gateway|gateway timeout|unavailable)?/i,
  /\b404\b|\bpage not found\b|\bnot found\b/i,
  /content unavailable/i,
];

// Returns true when `text` is an error / bot-block body (or empty / too short to be content).
// Conservative: a long real document (won't carry multiple distinct error markers) is NOT
// flagged — requires (short body AND >=1 marker) OR (>=2 distinct markers) OR (empty/tiny).
export function isErrorBody(text) {
  if (!text || text.trim().length < 60) return true;     // empty / tiny = no real content
  const head = text.slice(0, 2500);                       // error pages declare themselves early
  const hits = ERROR_SIGNATURES.filter((re) => re.test(head)).length;
  if (text.trim().length < 1500 && hits >= 1) return true; // short + an error marker = error page
  if (hits >= 2) return true;                              // multiple distinct markers = error page
  return false;
}
