-- ══════════════════════════════════════════════════════════════
-- Seed: Source Registry
-- ══════════════════════════════════════════════════════════════
--
-- These are the ACTUAL SOURCES — public portals where legislation
-- is published. Each entry is a website maintained by a government,
-- IGO, or authoritative body.
--
-- Tiers match the environmental-policy-and-innovation skill:
--   T1 = Primary legal text (official journals, gazettes)
--   T2 = Regulator implementation (official guidance portals)
--   T3 = Intergovernmental body (IMO, ICAO, UNFCCC, IEA)
--   T4 = Expert analysis (think tanks, academic trackers)
--   T5 = Industry and standards (ISO, GHG Protocol, FIATA)
--   T6 = News and commentary (Thomson Reuters, law firms)
--   T7 = Provisional (unverified discoveries)
--
-- Trust baselines:
--   T1=95, T2=85, T3=70, T4=50, T5=40, T6=25, T7=10
-- ══════════════════════════════════════════════════════════════


-- ════════════════════════════════════
-- TIER 1: Primary Legal Text
-- ════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, api_endpoint, status, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('EUR-Lex',
 'https://eur-lex.europa.eu',
 'The EU Official Journal and legal text portal. Publishes ALL EU legislation including directives, regulations, and decisions. Contains FuelEU Maritime, ReFuelEU Aviation, EU ETS, CBAM, CSRD, PPWR, EUDR, and every other EU legal instrument.',
 1, 1,
 ARRAY['REG','STD'],
 ARRAY[1,2,3,4],
 ARRAY['eu'],
 ARRAY['air','road','ocean'],
 'daily',
 'api',
 'https://eur-lex.europa.eu/content/help/data-reuse/webservice.html',
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'SOAP/XML webservice available. RSS alerts for OJ editions. Requires registration for API access.'),

('Federal Register',
 'https://www.federalregister.gov',
 'The daily journal of the US government. Publishes all federal rules, proposed rules, notices, and presidential documents. Contains EPA vehicle rules, DOT regulations, and all US federal rulemaking.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1,3],
 ARRAY['us'],
 ARRAY['air','road','ocean'],
 'business-daily',
 'api',
 'https://www.federalregister.gov/developers/documentation/api/v1',
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'Public JSON API with interactive documentation. Published Mon-Fri excluding federal holidays.'),

('Regulations.gov',
 'https://www.regulations.gov',
 'US federal docket and comment system. Tracks all active rulemakings, public comment periods, and supporting documents across all federal agencies.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1],
 ARRAY['us'],
 ARRAY['air','road','ocean'],
 'continuous',
 'api',
 'https://open.gsa.gov/api/regulationsgov/',
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'GET API for searching documents, comments, and dockets.'),

('UK Legislation',
 'https://www.legislation.gov.uk',
 'The official home of UK legislation. Contains all Acts of Parliament, Statutory Instruments, and related legislation including UK ETS, UK ZEV mandate, UK SAF mandate, UK EPR packaging.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1,3],
 ARRAY['uk'],
 ARRAY['air','road','ocean'],
 'daily',
 'api',
 NULL,
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'Provides XML/RDF feeds. Comprehensive UK legislative corpus.'),

('Gazette of India eGazette',
 'https://egazette.gov.in',
 'Official gazette of the Government of India. Publishes all central government notifications, rules, and regulations.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1,3],
 ARRAY['india'],
 ARRAY['air','road','ocean'],
 'continuous',
 'gazette',
 NULL,
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'English/Hindi. PDF-first publication. Requires HTML/PDF extraction.'),

('National Database of Laws and Regulations (China)',
 'https://flk.npc.gov.cn',
 'Official Chinese national law database maintained by the National People''s Congress. Contains all PRC laws and administrative regulations.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1,3],
 ARRAY['china'],
 ARRAY['air','road','ocean'],
 'continuous',
 'gazette',
 NULL,
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'Chinese language. Machine translation required for ingestion.'),

('Singapore Statutes Online',
 'https://sso.agc.gov.sg',
 'Official Singapore legislation portal maintained by the Attorney-General''s Chambers. Contains all current Singapore Acts and subsidiary legislation.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1,3],
 ARRAY['singapore'],
 ARRAY['air','road','ocean'],
 'continuous',
 'scrape',
 NULL,
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'English language. Well-structured HTML.'),

('Statutes of the Republic of Korea',
 'https://elaw.klri.re.kr/eng_service/main.do',
 'Official English translations of Korean statutes maintained by the Korea Legislation Research Institute.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1,3],
 ARRAY['korea'],
 ARRAY['air','road','ocean'],
 'continuous',
 'scrape',
 NULL,
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'English translations available. Updated as new translations are completed.'),

('Diario Oficial da Uniao (Brazil)',
 'https://www.gov.br/pt-br/servicos/acessar-o-diario-oficial-da-uniao',
 'Official gazette of the Brazilian federal government. Publishes all federal laws, decrees, and regulations.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1,3],
 ARRAY['brazil'],
 ARRAY['air','road','ocean'],
 'daily',
 'gazette',
 NULL,
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'Portuguese language. Daily publication via Imprensa Nacional.'),

('Ley Chile',
 'https://www.bcn.cl/leychile',
 'Official Chilean legislative database maintained by the National Library of Congress.',
 1, 1,
 ARRAY['REG'],
 ARRAY[1,3],
 ARRAY['latam'],
 ARRAY['road','ocean'],
 'continuous',
 'scrape',
 NULL,
 'active',
 95, 38.0, 19.0, 19.0, 19.0,
 'Spanish language.');


-- ════════════════════════════════════
-- TIER 2: Regulator Implementation
-- ════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('US EPA Emissions Regulations',
 'https://www.epa.gov/regulations-emissions-vehicles-and-engines',
 'EPA rule and program pages for vehicle and engine emissions. Contains final rules, rule summaries, and implementation guidance for US vehicle GHG standards.',
 2, 2,
 ARRAY['REG','STD'],
 ARRAY[1,2],
 ARRAY['us'],
 ARRAY['road'],
 'ad-hoc',
 'scrape',
 'active',
 85, 34.0, 17.0, 17.0, 17.0,
 'Ad hoc updates. High activity during rulemakings. Rule summaries are authoritative interpretations.'),

('Council of the European Union Press',
 'https://www.consilium.europa.eu/en/press/press-releases/',
 'Official political and legal status updates from the EU Council. Publishes decisions on legislation adoption, political agreements, and voting results.',
 2, 2,
 ARRAY['REG'],
 ARRAY[1,4],
 ARRAY['eu'],
 ARRAY['air','road','ocean'],
 'continuous',
 'rss',
 'active',
 85, 34.0, 17.0, 17.0, 17.0,
 'RSS feeds available at https://www.consilium.europa.eu/en/about-site/rss/'),

('European Commission Press Corner',
 'https://ec.europa.eu/commission/presscorner/home/en',
 'Official policy communications from the European Commission. Publishes legislative proposals, impact assessments, and policy announcements.',
 2, 2,
 ARRAY['REG','IND'],
 ARRAY[1,2,4],
 ARRAY['eu'],
 ARRAY['air','road','ocean'],
 'daily',
 'rss',
 'active',
 85, 34.0, 17.0, 17.0, 17.0,
 'Email notifications supported via saved searches.'),

('EC DG CLIMA Shipping',
 'https://climate.ec.europa.eu/eu-action/transport-decarbonisation/reducing-emissions-shipping-sector_en',
 'European Commission DG CLIMA shipping decarbonization pages. Contains EU Maritime ETS FAQ, FuelEU Maritime implementation guidance, and MRV requirements.',
 2, 2,
 ARRAY['REG','STD'],
 ARRAY[1,2],
 ARRAY['eu'],
 ARRAY['ocean'],
 'ad-hoc',
 'scrape',
 'active',
 85, 34.0, 17.0, 17.0, 17.0,
 'Updated as implementation evolves. Key source for maritime ETS phase-in details.'),

('EC CBAM Portal',
 'https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en',
 'European Commission CBAM implementation portal. Contains transitional registry, reporting templates, guidance documents, and FAQ.',
 2, 2,
 ARRAY['REG'],
 ARRAY[1,4],
 ARRAY['eu'],
 ARRAY['air','road','ocean'],
 'ad-hoc',
 'scrape',
 'active',
 85, 34.0, 17.0, 17.0, 17.0,
 'Active during transitional reporting deadlines. Direct source for CBAM compliance requirements.'),

('THETIS-MRV',
 'https://mrv.emsa.europa.eu',
 'European Maritime Safety Agency MRV reporting system. Contains public shipping emissions data reported under EU MRV Regulation.',
 2, 2,
 ARRAY['REG','MKT'],
 ARRAY[1,6],
 ARRAY['eu'],
 ARRAY['ocean'],
 'continuous',
 'scrape',
 'active',
 85, 34.0, 17.0, 17.0, 17.0,
 'Operational reporting system. Annual reporting cycles with continuous data collection.');


-- ════════════════════════════════════
-- TIER 3: Intergovernmental Bodies
-- ════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('International Maritime Organization',
 'https://www.imo.org',
 'UN specialized agency responsible for shipping regulation. Publishes IMO GHG Strategy, MEPC resolutions, net-zero framework, and all maritime environmental regulations.',
 3, 3,
 ARRAY['REG','SUP','STD'],
 ARRAY[1,2],
 ARRAY['global','imo'],
 ARRAY['ocean'],
 'ad-hoc',
 'scrape',
 'active',
 70, 28.0, 14.0, 14.0, 14.0,
 'Activity spikes around MEPC sessions. Meeting summaries at /en/mediacentre/meetingsummaries/'),

('International Civil Aviation Organization',
 'https://www.icao.int/CORSIA',
 'ICAO CORSIA portal. Publishes Carbon Offsetting and Reduction Scheme for International Aviation standards, eligible fuels, monitoring guidelines.',
 3, 3,
 ARRAY['REG','SUP','STD'],
 ARRAY[1,2],
 ARRAY['global','icao'],
 ARRAY['air'],
 'ad-hoc',
 'scrape',
 'active',
 70, 28.0, 14.0, 14.0, 14.0,
 'Periodic updates and newsletters. Key source for SAF eligibility and aviation offsetting.'),

('UNFCCC NDC Registry',
 'https://unfccc.int/NDCREG',
 'UN Framework Convention on Climate Change registry of Nationally Determined Contributions. Tracks country-level climate commitments.',
 3, 3,
 ARRAY['REG','SUP'],
 ARRAY[1,4],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'scrape',
 'active',
 70, 28.0, 14.0, 14.0, 14.0,
 'Updated as Parties submit. Useful for understanding jurisdiction-level ambition.'),

('World Bank Carbon Pricing Dashboard',
 'https://carbonpricingdashboard.worldbank.org',
 'Global dataset of carbon pricing instruments. Tracks ETS prices, carbon taxes, and coverage across all jurisdictions.',
 3, 3,
 ARRAY['MKT','REG'],
 ARRAY[1,4],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'monthly',
 'scrape',
 'active',
 70, 28.0, 14.0, 14.0, 14.0,
 'Dashboard maintained continuously. Key source for Domain 4 carbon market tracking.'),

('IEA Policies and Measures Database',
 'https://www.iea.org/policies/about',
 'International Energy Agency policy database. Inventory of energy and climate policies across countries.',
 3, 3,
 ARRAY['REG','MKT','RES'],
 ARRAY[1,2,3],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 70, 28.0, 14.0, 14.0, 14.0,
 'Regular updates. Cross-country policy comparison.');


-- ════════════════════════════════════
-- TIER 4: Expert Analysis
-- ════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('Climate Change Laws of the World',
 'https://climate-laws.org',
 'Grantham Research Institute / LSE database of climate legislation and litigation worldwide. Comprehensive tracker of national climate laws.',
 4, 4,
 ARRAY['REG','RES'],
 ARRAY[1,7],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'monthly',
 'scrape',
 'active',
 50, 20.0, 10.0, 10.0, 10.0,
 'Academic/NGO tracker. Good gap-filler for jurisdictions where official sources lack English.'),

('ECOLEX',
 'https://www.ecolex.org',
 'Joint FAO/IUCN/UNEP environmental law database. Aggregates treaties, national legislation, and related materials.',
 4, 4,
 ARRAY['REG','RES'],
 ARRAY[1,7],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'monthly',
 'scrape',
 'active',
 50, 20.0, 10.0, 10.0, 10.0,
 'Useful for covering jurisdictions where official gazettes lack friendly English tooling.'),

('Sabin Center for Climate Change Law',
 'https://climate.law.columbia.edu',
 'Columbia Law School climate litigation and regulatory tracker. Specialized in anticipating litigation-driven regulatory risk.',
 4, 4,
 ARRAY['REG','RES'],
 ARRAY[1,7],
 ARRAY['us','global'],
 ARRAY['air','road','ocean'],
 'weekly',
 'scrape',
 'active',
 50, 20.0, 10.0, 10.0, 10.0,
 'Particularly useful for US regulatory whiplash and climate deregulation/reregulation tracking.'),

('European Environment Agency',
 'https://www.eea.europa.eu',
 'EU agency providing independent environmental information. Publishes sectoral analysis including maritime decarbonization progress.',
 4, 4,
 ARRAY['RES','MKT'],
 ARRAY[1,2,3],
 ARRAY['eu'],
 ARRAY['air','road','ocean'],
 'monthly',
 'rss',
 'active',
 50, 20.0, 10.0, 10.0, 10.0,
 'Official-style analysis tied to EU policy packages. Maritime transport news feed available.'),

('ICCT Freight',
 'https://theicct.org/sector/freight/',
 'International Council on Clean Transportation freight sector analysis. Policy-relevant research specific to freight, aviation, and fuel pathways.',
 4, 4,
 ARRAY['RES','INN'],
 ARRAY[1,2],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'monthly',
 'scrape',
 'active',
 50, 20.0, 10.0, 10.0, 10.0,
 'High-quality operational impact analysis. Useful for "what this means for freight forwarding" reasoning.'),

('International Transport Forum',
 'https://www.itf-oecd.org/decarbonising-transport',
 'OECD transport arm. Transport decarbonization frameworks and comparable cross-country transport policy analysis.',
 4, 4,
 ARRAY['RES','STD'],
 ARRAY[1,2],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 50, 20.0, 10.0, 10.0, 10.0,
 'Cross-country transport decarbonization comparisons.');


-- ════════════════════════════════════
-- TIER 5: Industry and Standards
-- ════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('ISO 14083',
 'https://www.iso.org/standard/78864.html',
 'ISO standard for quantification and reporting of greenhouse gas emissions arising from transport chain operations. Increasingly a contractual requirement in freight tenders.',
 5, 5,
 ARRAY['STD'],
 ARRAY[1,5],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'ad-hoc',
 'manual',
 'active',
 40, 16.0, 8.0, 8.0, 8.0,
 'Standard itself is paywalled. Implementation guidance and adoption tracking are the monitoring targets.'),

('Smart Freight Centre / GLEC Framework',
 'https://www.smartfreightcentre.org/en/our-programs/emissions-accounting/global-logistics-emissions-council/',
 'Curates the Global Logistics Emissions Council Framework — industry cornerstone for transparent logistics emissions accounting.',
 5, 5,
 ARRAY['STD','IND'],
 ARRAY[1,5],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 40, 16.0, 8.0, 8.0, 8.0,
 'GLEC Framework aligned with ISO 14083. Practical basis for forwarder-facing carbon reporting.'),

('GHG Protocol',
 'https://ghgprotocol.org/corporate-value-chain-scope-3-standard',
 'De facto global accounting standards for value-chain emissions (Scope 3). Drives customer questionnaires and tender requirements faced by forwarders.',
 5, 5,
 ARRAY['STD'],
 ARRAY[1,5],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'ad-hoc',
 'scrape',
 'active',
 40, 16.0, 8.0, 8.0, 8.0,
 'Foundation standard — SBTi, CDP, CSRD all build on this.'),

('Science Based Targets initiative',
 'https://sciencebasedtargets.org',
 'Publishes transport-specific target-setting guidance. Helps align internal KPI recommendations with customer and investor expectations.',
 5, 5,
 ARRAY['STD','IND'],
 ARRAY[1,5],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 40, 16.0, 8.0, 8.0, 8.0,
 'Land transport guidance PDF: https://files.sciencebasedtargets.org/production/files/Land-Transport-Guidance.pdf'),

('CDP Supply Chain',
 'https://www.cdp.net/en/supply-chain',
 'Major channel through which customers request supplier emissions data. Supply-chain program scale makes it relevant to forwarder data strategy.',
 5, 5,
 ARRAY['STD','IND'],
 ARRAY[1,5],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'annual',
 'scrape',
 'active',
 40, 16.0, 8.0, 8.0, 8.0,
 'Annual disclosure cycle. Increasingly tied to procurement decisions.'),

('IFRS / ISSB Sustainability Standards',
 'https://www.ifrs.org/sustainability/knowledge-hub/introduction-to-issb-and-ifrs-sustainability-disclosure-standards/',
 'ISSB sustainability disclosure standards (IFRS S1/S2). Influences disclosure expectations across multiple jurisdictions.',
 5, 5,
 ARRAY['STD','REG'],
 ARRAY[1,5],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 40, 16.0, 8.0, 8.0, 8.0,
 'Jurisdictional adoption tracker is key monitoring target.'),

('FIATA Sustainability',
 'https://fiata.org/sustainability-is-a-critical-issue-facing-our-world/',
 'International Federation of Freight Forwarders Associations. Provides forwarder-specific interpretation, positions, and practical guidance.',
 5, 5,
 ARRAY['IND'],
 ARRAY[1,5],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 40, 16.0, 8.0, 8.0, 8.0,
 'Speaks the forwarder operational language. CBAM guidance, emissions accounting standard guides.'),

('IRU Environment',
 'https://www.iru.org/what-we-do/being-trusted-voice-mobility-and-logistics/environment',
 'International Road Transport Union environmental positions and commitments. Road-freight sector context for trucks, drayage, fleet transition.',
 5, 5,
 ARRAY['IND'],
 ARRAY[1,2],
 ARRAY['global'],
 ARRAY['road'],
 'quarterly',
 'scrape',
 'active',
 40, 16.0, 8.0, 8.0, 8.0,
 'Road-freight specific. Fleet transition impact context.');


-- ════════════════════════════════════
-- TIER 6: News and Commentary
-- ════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('Thomson Reuters Regulatory Intelligence',
 'https://regintel-content.thomsonreuters.com',
 'Commercial regulatory intelligence service. Curated change events mapping across thousands of regulators with API integration.',
 6, 6,
 ARRAY['REG','MKT'],
 ARRAY[1,4],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'daily',
 'api',
 'active',
 25, 10.0, 5.0, 5.0, 5.0,
 'Commercial / paywalled. Useful when internal capacity for parsing non-English primary sources is limited.');


-- ══════════════════════════════════════════════════════════════
-- DOMAIN 2: Energy and Technology Innovation Sources
-- ══════════════════════════════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, paywalled, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('IEA Data and Statistics Hub',
 'https://www.iea.org/data-and-statistics/data-explorers',
 'IEA interactive data portal covering EV sales, battery costs, charging infrastructure, hydrogen projects, SAF data, and technology deployment by country.',
 1, 1,
 ARRAY['MKT','INN','RES'],
 ARRAY[2],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'api',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Continuous updates with annual flagship reports. Interactive data explorers with downloadable datasets.'),

('IEA Global Hydrogen Review',
 'https://www.iea.org/reports/global-hydrogen-review-2025',
 'Annual IEA flagship on green hydrogen cost curves, project tracker, infrastructure deployment by region, and marine fuel outlook.',
 1, 1,
 ARRAY['RES','INN','MKT'],
 ARRAY[2],
 ARRAY['global'],
 ARRAY['ocean','road'],
 'annual',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Annual publication. Key source for hydrogen cost curves and refueling infrastructure by corridor.'),

('IEA World Energy Outlook Dataset',
 'https://www.iea.org/data-and-statistics/data-product/world-energy-outlook-2025-free-dataset',
 'IEA long-range energy technology scenarios, cost trajectories, and capacity projections. Free dataset from the World Energy Outlook.',
 1, 1,
 ARRAY['MKT','RES'],
 ARRAY[2,4],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'annual',
 'manual',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Free dataset. Scenario-based projections for energy technology deployment and cost evolution.'),

('IRENA Renewable Power Generation Costs',
 'https://www.irena.org/Energy-Transition/Technology/Power-generation-costs',
 'IRENA database of solar PV, wind, and BESS cost curves from 20,000+ projects. Annual cost benchmarks for renewable energy technologies.',
 1, 1,
 ARRAY['MKT','RES','INN'],
 ARRAY[2,6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'annual',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 '2024 edition published July 2025. Key source for BESS commercial pricing trajectory and solar ROI inputs.'),

('IRENA Data Portal',
 'https://www.irena.org/Data',
 'IRENA renewable capacity, generation, and energy balance statistics by country. Statistics questionnaire data from member states.',
 1, 1,
 ARRAY['MKT','RES'],
 ARRAY[2,6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'annual',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Capacity data annual March, generation data annual July.'),

('IRENA Publications',
 'https://www.irena.org/Publications',
 'IRENA technology reports covering sodium-ion batteries, solar supply chain costs, hydrogen, SAF, marine fuels, and energy transition finance.',
 1, 1,
 ARRAY['RES','INN'],
 ARRAY[2],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Continuous publication of technology-specific reports.'),

('US DOE Clean Investment Monitor',
 'https://www.cleaninvestmentmonitor.org',
 'US investment tracker for hydrogen, SAF, BESS, and carbon management. Project-level final investment decision tracking.',
 2, 2,
 ARRAY['MKT','INN'],
 ARRAY[2,4],
 ARRAY['us'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Quarterly updates. Tracks actual investment deployment, not just announcements.'),

('RMI Energy Innovation',
 'https://rmi.org',
 'Rocky Mountain Institute research on battery technology trajectories, solid-state commercialization timelines, hydrogen infrastructure, and clean freight pathways.',
 3, 3,
 ARRAY['RES','INN'],
 ARRAY[2],
 ARRAY['global'],
 ARRAY['road','ocean'],
 'continuous',
 'scrape',
 'active',
 FALSE,
 70, 28.0, 14.0, 14.0, 14.0,
 'Continuous research publications. Strong on battery and hydrogen analysis.');


-- ══════════════════════════════════════════════════════════════
-- DOMAIN 3: Regional Operations Intelligence Sources
-- ══════════════════════════════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, paywalled, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('IEA Energy Prices Database',
 'https://www.iea.org/data-and-statistics/data-product/energy-prices',
 'Industrial electricity tariffs for 130 countries with sector breakdown. Quarterly OECD updates, annual global data.',
 1, 1,
 ARRAY['MKT'],
 ARRAY[3,6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'api',
 'active',
 TRUE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Partial paywall — some datasets require subscription. Key source for Domain 6 facility cost benchmarking.'),

('NREL NSRDB National Solar Radiation Database',
 'https://nsrdb.nrel.gov/',
 'Solar irradiance data (GHI, DNI, DHI) globally at 4km resolution, 30-minute intervals. Free API access.',
 1, 1,
 ARRAY['MKT','RES'],
 ARRAY[3,6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'api',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'US complete coverage, international expanding. Free API for automated ingestion of solar resource data.'),

('Solargis Global Solar Atlas',
 'https://globalsolaratlas.info',
 'Global solar resource data by city and region. Rooftop solar yield estimates for any location worldwide.',
 1, 1,
 ARRAY['MKT'],
 ARRAY[3,6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'annual',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'World Bank funded. Key input for rooftop solar ROI calculations by jurisdiction.'),

('NREL PVWatts Calculator',
 'https://pvwatts.nrel.gov',
 'Rooftop solar ROI modeling tool. Grid-connected system energy production and cost estimates for any location worldwide.',
 1, 1,
 ARRAY['MKT'],
 ARRAY[6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'api',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Continuous tool updates. API available for automated ROI calculations.'),

('DEWA Shams Dubai Program',
 'https://www.dewa.gov.ae/en/consumers/innovation/shams-dubai',
 'Dubai rooftop solar net metering program terms for commercial and industrial properties. Version 4 (June 2022) confirms commercial solar is permitted with net metering. Active open question: verify current status and any subsequent amendments.',
 1, 1,
 ARRAY['REG','MKT'],
 ARRAY[3,1],
 ARRAY['uae','meaf'],
 ARRAY['air','road','ocean'],
 'ad-hoc',
 'scrape',
 'provisional',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'STATUS: PROVISIONAL — requires live verification against current DEWA portal. Contradicts a claim that commercial rooftop solar is prohibited in Dubai. This is the model for regional intelligence gap-closing.'),

('ILOSTAT',
 'https://ilostat.ilo.org/',
 'ILO global labor statistics: wages, labor costs, and earnings by country and sector. 300M+ data points across 200 countries.',
 1, 1,
 ARRAY['MKT'],
 ARRAY[3,6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'api',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Free API access. Annual Global Wage Report. Key source for labor cost benchmarks by country and role.'),

('ILO Global Wage Report',
 'https://www.ilo.org/resource/other/global-wage-report-series',
 'Country-level average wages, real wage growth, and labor cost benchmarks by region. 2024-25 edition current.',
 1, 1,
 ARRAY['RES','MKT'],
 ARRAY[3,6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'annual',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Annual publication. Complements ILOSTAT for narrative analysis of labor cost trends.'),

('USGBC LEED Project Database',
 'https://www.usgbc.org/projects',
 'LEED-certified projects and certification requirements by country and building type. Searchable project database.',
 2, 2,
 ARRAY['STD'],
 ARRAY[3,6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Key source for green building certification tracking. Global coverage.'),

('BREEAM (BRE Global)',
 'https://www.breeam.com',
 'UK and European green building certification requirements and standards for commercial properties.',
 2, 2,
 ARRAY['STD'],
 ARRAY[3,6],
 ARRAY['eu','uk'],
 ARRAY['air','road','ocean'],
 'ad-hoc',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Primary green building standard for UK and Europe.'),

('Estidama Pearl Rating System',
 'https://www.abudhabi.ae/en/infrastructure-environment/environment/estidama',
 'UAE green building certification requirements for commercial and industrial buildings in Abu Dhabi.',
 2, 2,
 ARRAY['STD','REG'],
 ARRAY[3,6],
 ARRAY['uae','meaf'],
 ARRAY['air','road','ocean'],
 'ad-hoc',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Abu Dhabi specific. Mandatory for certain building categories.'),

('Singapore BCA Green Mark',
 'https://www1.bca.gov.sg/buildsg/sustainability/green-mark-certification-scheme',
 'Singapore green building certification scheme. Mandatory for new commercial buildings above certain thresholds.',
 2, 2,
 ARRAY['STD','REG'],
 ARRAY[3,6],
 ARRAY['singapore'],
 ARRAY['air','road','ocean'],
 'ad-hoc',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Mandatory certification for new buildings. Key for Singapore warehouse facility planning.');


-- ══════════════════════════════════════════════════════════════
-- DOMAIN 4: Geopolitical and Market Signals Sources
-- ══════════════════════════════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, paywalled, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('US EIA Short-Term Energy Outlook',
 'https://www.eia.gov/outlooks/steo/',
 'Brent crude price forecasts, jet fuel projections, US production data. Includes Strait of Hormuz supply impact modeling.',
 1, 1,
 ARRAY['MKT'],
 ARRAY[4],
 ARRAY['global'],
 ARRAY['air','ocean','road'],
 'monthly',
 'api',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Monthly publication. Key source for fuel cost forecasting.'),

('US EIA Petroleum Spot Prices',
 'https://www.eia.gov/dnav/pet/pet_pri_spt_s1_d.htm',
 'Daily Brent crude, WTI, and jet fuel spot prices with historical data.',
 1, 1,
 ARRAY['MKT'],
 ARRAY[4],
 ARRAY['global'],
 ARRAY['air','ocean','road'],
 'daily',
 'api',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Daily updates. Direct input for freight cost modeling.'),

('US EIA Open Data API',
 'https://www.eia.gov/opendata/',
 'Full US EIA data API covering petroleum, natural gas, electricity, and coal datasets. Free API key access for automated ingestion.',
 1, 1,
 ARRAY['MKT'],
 ARRAY[4,2],
 ARRAY['us','global'],
 ARRAY['air','ocean','road'],
 'continuous',
 'api',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Free API. Covers all EIA data series. Key infrastructure for automated price monitoring.'),

('ICAP Allowance Price Explorer',
 'https://icapcarbonaction.com/en/ets-prices',
 'Carbon allowance prices for 38 ETS systems worldwide: EU ETS, UK ETS, California, RGGI, Korea, Singapore. Downloadable data.',
 1, 1,
 ARRAY['MKT','REG'],
 ARRAY[4,1],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Primary source for cross-jurisdictional carbon price comparison.'),

('ICAP Emissions Trading Status Report',
 'https://icapcarbonaction.com',
 'Annual global ETS status: 38 systems in force, 11 under development. System factsheets and price analysis.',
 1, 1,
 ARRAY['MKT','REG','RES'],
 ARRAY[4,1],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'annual',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 '2026 edition publishes April 15, 2026. Comprehensive annual reference.'),

('EEA EU ETS Data Viewer',
 'https://www.eea.europa.eu/en/analysis/maps-and-charts/emissions-trading-viewer-1-dashboards',
 'EU ETS verified emissions, allocated allowances, and auctioned volumes. Official data from Union Registry and ICE/EEX.',
 1, 1,
 ARRAY['MKT','REG'],
 ARRAY[4,1],
 ARRAY['eu'],
 ARRAY['air','ocean'],
 'annual',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Annual extraction (July). Official EU ETS compliance data.'),

('IEA Electricity Mid-Year Update',
 'https://www.iea.org/reports/electricity-mid-year-update-2025',
 'Regional electricity demand forecasts, wholesale price trends, and gas price impacts on freight operating costs.',
 1, 1,
 ARRAY['MKT','RES'],
 ARRAY[4,3],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'quarterly',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Semi-annual publication. Links energy markets to freight cost drivers.'),

('MarineTraffic',
 'https://www.marinetraffic.com',
 'Live tanker traffic through Strait of Hormuz and global shipping lanes. Vessel positions, port calls, congestion indicators.',
 2, 2,
 ARRAY['MKT'],
 ARRAY[4],
 ARRAY['global'],
 ARRAY['ocean'],
 'continuous',
 'api',
 'active',
 TRUE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Partial paywall: basic free, AIS data requires subscription. Real-time vessel tracking.'),

('J.P. Morgan Eye on the Market (Cembalest)',
 'https://am.jpmorgan.com/us/en/asset-management/adv/insights/market-insights/eye-on-the-market/',
 'Country energy insulation rankings, commodity analysis, and geopolitical market signals. Pandora''s Bog series covers energy independence metrics.',
 3, 3,
 ARRAY['MKT','RES'],
 ARRAY[4],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'weekly',
 'scrape',
 'active',
 FALSE,
 70, 28.0, 14.0, 14.0, 14.0,
 'Registration required but not paywalled. Michael Cembalest heat map is quarterly update target.');


-- ══════════════════════════════════════════════════════════════
-- DOMAIN 6: Warehouse and Facility Optimization Sources
-- (IEA Energy Prices, NREL, Solargis, PVWatts, ILOSTAT, IRENA
--  already added above — not duplicated here)
-- ══════════════════════════════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, paywalled, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('NREL System Advisor Model (SAM)',
 'https://sam.nrel.gov',
 'Detailed solar ROI modeling tool with BESS integration. Commercial and industrial system sizing for any location.',
 1, 1,
 ARRAY['MKT'],
 ARRAY[6],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'manual',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Downloadable software. More detailed than PVWatts for commercial system design.'),

('BloombergNEF Energy Storage',
 'https://about.bnef.com/energy-storage/',
 'BESS cost trajectories, commercial battery storage pricing, lithium-ion and alternative chemistry cost curves.',
 2, 2,
 ARRAY['MKT','RES'],
 ARRAY[6,2],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'annual',
 'manual',
 'active',
 TRUE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Paywalled subscription. Annual flagship report plus continuous research notes. Key for BESS pricing trajectory.');


-- ══════════════════════════════════════════════════════════════
-- DOMAIN 7: University and Research Pipeline Sources
-- ══════════════════════════════════════════════════════════════

INSERT INTO sources (name, url, description, tier, tier_at_creation, intelligence_types, domains, jurisdictions, transport_modes, update_frequency, access_method, status, paywalled, trust_score_overall, trust_score_accuracy, trust_score_timeliness, trust_score_reliability, trust_score_citation, notes) VALUES

('MIT Climate Machine',
 'https://climatemachine.mit.edu',
 'MIT Environmental Solutions Initiative live music emissions research. Phase 1 published December 11, 2025 covering 80,000+ events across US and UK. Verified primary source for live events sector research.',
 1, 1,
 ARRAY['RES'],
 ARRAY[7],
 ARRAY['us','uk'],
 ARRAY['air','road'],
 'ad-hoc',
 'scrape',
 'active',
 FALSE,
 95, 38.0, 19.0, 19.0, 19.0,
 'Phase 1 complete. Phase 2 forthcoming. Verify direct report download link before automated ingestion.'),

('MIT Center for Transportation and Logistics',
 'https://ctl.mit.edu',
 'Sustainable freight research, trucking consortium publications, and supply chain decarbonization research.',
 2, 2,
 ARRAY['RES'],
 ARRAY[7],
 ARRAY['global'],
 ARRAY['air','road','ocean'],
 'continuous',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Active sustainable trucking consortium (2025). Broad transport logistics research.'),

('Tyndall Centre for Climate Research',
 'https://www.tyndall.ac.uk',
 'ACT 1.5 low-carbon concert roadmap (2025). Massive Attack concert case study. Live events decarbonization pathway research.',
 2, 2,
 ARRAY['RES'],
 ARRAY[7],
 ARRAY['uk','global'],
 ARRAY['air','road'],
 'ad-hoc',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'ACT 1.5 report published 2025. Ongoing live music roadmap work.'),

('Chalmers University Marine Environment',
 'https://www.chalmers.se/en/departments/m2/',
 'Marine decarbonization research: alternative fuel readiness for shipping, LNG, methanol, ammonia pathways.',
 2, 2,
 ARRAY['RES'],
 ARRAY[7],
 ARRAY['global'],
 ARRAY['ocean'],
 'ad-hoc',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Swedish university. Strong marine fuel pathway research.'),

('Centre for Sustainable Road Freight',
 'https://www.csrf.ac.uk',
 'UK road freight decarbonization research. Zero-emission HGV pathways. Charging infrastructure for logistics operations.',
 2, 2,
 ARRAY['RES'],
 ARRAY[7],
 ARRAY['uk'],
 ARRAY['road'],
 'ad-hoc',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'Heriot-Watt / Cambridge collaboration.'),

('Julie''s Bicycle',
 'https://juliesbicycle.com',
 'Creative Climate Tools updates. Arts and entertainment sustainability guides. Industry benchmark reports for the cultural sector.',
 2, 2,
 ARRAY['RES','IND'],
 ARRAY[7],
 ARRAY['uk','global'],
 ARRAY['road','air'],
 'annual',
 'scrape',
 'active',
 FALSE,
 85, 34.0, 17.0, 17.0, 17.0,
 'UK arts sector focus. Creative Climate Tools are a practical resource for cultural organizations.'),

('REVERB',
 'https://reverb.org',
 'Annual Music on a Mission tour impact reports. Festival sustainability data. Vendor and supplier recommendations for live events.',
 3, 3,
 ARRAY['RES','IND'],
 ARRAY[7],
 ARRAY['us'],
 ARRAY['road','air'],
 'annual',
 'scrape',
 'active',
 FALSE,
 70, 28.0, 14.0, 14.0, 14.0,
 'US live music focus. Annual impact reports are key benchmarking data for live events vertical.');
