-- ══════════════════════════════════════════════════════════════
-- Seed: Community Layer — Taxonomy + Case Studies
-- ══════════════════════════════════════════════════════════════
--
-- The forum_sections INSERT blocks (8 regional + 9 topical, mig-007 layer) were
-- REMOVED 2026-07-11 (Wave-α Track D d4): the forum_* layer is a dead parallel
-- implementation with zero code paths — superseded by the community_groups
-- conversation layer — and migration 192 drops the tables. Re-adding the seed
-- would re-seed a table that no longer exists. Prior revision in git history
-- (docs/ops/wave-alpha-closeout-2026-07-11/deletions-log.md records the snapshot).
--
-- The taxonomy_nodes (38 rows) and case_studies (6 rows) INSERT blocks that used
-- to live below this comment were REMOVED 2026-09-29 (Lane DROP-PLACEHOLDERS,
-- operator ruling: "There has never been anyone in community so my guess is they
-- are fake place holders. Remove them completely and ease them"). Both tables +
-- case_study_endorsements are dropped by migration 335. Re-adding this seed
-- would re-seed tables that no longer exist. Prior revision in git history
-- (docs/ops/session-log.d/2026-09-29-drop-placeholders.md records the snapshot;
-- row data also snapshotted to fsi-app/scripts/tmp/drop-placeholders-2026-09-29/,
-- gitignored).
