// RD-68: split from invariants.mjs (plan 6.8, Rule A, lane N5). One entry, one file; see
// invariants.d/README.md. The comment block below (if any) is exactly what preceded this entry in
// the array before the split.

export const invariant = {
    id: 'RD-68',
    skill: 'remediation-discipline',
    section: 'Section 4 - category 44: a CLI main guard built from a hand-typed file:// string breaks on every Windows machine',
    text: 'A CLI entry-point guard under fsi-app/scripts/** or fsi-app/.discipline/** must compare import.meta.url against a URL built from process.argv[1] through Node\'s own pathToFileURL/resolve, never a hand-typed file:// string concatenation. [CONFIRMED, task 0.3b, 2026-09-11, by grep across scripts/** and .discipline/**]: 36 files used a guard that compared import.meta.url, with the === operator, against a template literal built by prefixing the six characters "file://" onto process.argv[1], then calling main() when it matched. On Windows, import.meta.url is a real file:// URL with forward slashes while process.argv[1] is a native backslash path, so the hand-built comparison string never equals import.meta.url and the guard is never true. [CORRECTED, fix round 1, reviewer-confirmed]: 31 of the 36 files had no fallback and silently exited 0 with no output when invoked directly on Windows, a runtime defect caught only because the pre-push suite\'s spawned-CLI tests returned empty stdout on the operator\'s Windows machine while the identical tests passed on Linux CI; the other 5 (skill-map.mjs, skill-contract-map.mjs, bootstrap-test1.mjs, defect-signature-scan.mjs, no-generic-source-audit.mjs) carried a working `|| process.argv[1]?.endsWith(...)` fallback naming their own filename, which still called main() correctly despite the broken primary comparison, fragile but not silently broken. (The exact broken idiom is not reproduced verbatim in this text because this file itself falls under F44\'s scanned tree; see F44-broken-main-guard.mjs\'s own header for the literal form.)',
    anchor: '### Section 4 - category 44: a CLI main guard built from a hand-typed file:// string breaks on every Windows machine',
    enforcedBy: [
      'fitness:F44',
      'selftest:fsi-app/.discipline/fitness/functions/F44-broken-main-guard.test.mjs',
      'selftest:fsi-app/scripts/lib/is-main.test.mjs',
    ],
    residual: 'F44 and is-main.test.mjs are both LEXICAL scanners (regex over file content, comment lines skipped) matching the exact broken idiom, with or without a trailing `|| process.argv[1]?.endsWith(...)` fallback some call sites had already grown as a partial workaround; a guard rewritten into some other broken shape not carrying that literal text would not be caught by either. Both scan the same two trees (fsi-app/scripts/** and fsi-app/.discipline/**) for redundancy across the two lanes that exercise them (F44 in the fitness runner, is-main.test.mjs in the no-npm-ci pre-push suite) rather than for independent coverage. isMainModule() itself (scripts/lib/is-main.mjs) is unit-tested by both a real `node <file>` spawn (proving Windows argv[1]/import.meta.url parity, not a mocked in-process override) and direct-call cases for the false branches. `.discipline/governance/skill-map.mjs` and `skill-contract-map.mjs` inline the equivalent pathToFileURL/resolve comparison rather than importing scripts/lib/is-main.mjs, since `.discipline/governance/` carries no precedent for importing scripts/lib as an ES import (unlike `.discipline/fitness/functions/`, which already does via F28); a future change establishing that precedent could switch them to the shared import without changing behavior.',
  };
