// node --test proof that the committed design-audit results are CI's, not a developer machine's
// (lane DAUDIT-3, 2026-10-08).
//
// WHY. DAUDIT-2 diffed the green CI run's artifact against the results.json it had committed from Windows and
// 4 rows differed (the ch width of the vendored font, a 44px target), both with 0 harness errors. A computed
// style depends on the machine that measured it, so a committed oracle that depends on the committing machine
// is a defect. The generator now stamps `generated_on: { platform, node, container_image }` into results.json
// and into the audit document's Repo state block (run-audit.mjs, one site: generatedOn), and this test refuses
// a committed results.json or audit document whose platform is not linux. design-audit.yml commits both back
// from its workflow_dispatch path, so the only way a linux stamp lands in the repo is a CI run.
//
// INTENDED RED. On the commit that introduced this test the committed results.json had no stamp (it was
// generated on Windows by DAUDIT-2), so the "committed files" test fails until a workflow_dispatch of
// design-audit.yml commits the CI-generated pair back to the branch. That is the point of the test.
//
// PORTABLE: node builtins only (run-audit.mjs itself imports esbuild through the harness, so it is read as
// text and its one stamping function is extracted and run, never imported).
//
// PROVEN BY ATTACK (CLAUDE.md rule 15): the checker is also run against a win32 stamp, a darwin stamp, a missing
// stamp, a document without the stamp line and a document that disagrees with results.json; each must be
// reported.

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const REPO = join(HERE, '..', '..', '..', '..');
const RESULTS = JSON.parse(readFileSync(join(HERE, 'results.json'), 'utf8'));
const DOCUMENT = readFileSync(join(REPO, 'docs', 'design', 'handoff-2026-09-06', 'AUDIT-2026-09-07.md'), 'utf8');
const GENERATOR = readFileSync(join(HERE, 'run-audit.mjs'), 'utf8');

const STAMP_LINE = /^- Generated on: platform `([^`]+)`, node `([^`]+)`, container image `([^`]+)`$/m;

/** Every defect in a results object and its audit document, as short strings; empty means the pair is CI's. */
function stampProblems(results, documentText) {
  const out = [];
  const g = results.generated_on;
  if (!g || typeof g !== 'object') {
    out.push('results.json has no generated_on stamp (it was not produced by the stamping generator)');
  } else {
    if (g.platform !== 'linux') out.push(`results.json platform is ${JSON.stringify(g.platform)}, not linux (a committed oracle is CI's)`);
    if (typeof g.node !== 'string' || !/^v\d+\./.test(g.node)) out.push('results.json generated_on.node is not a node version');
    if (typeof g.container_image !== 'string' || g.container_image === '') out.push('results.json generated_on.container_image is empty');
  }
  const m = documentText.match(STAMP_LINE);
  if (!m) {
    out.push('the audit document has no "Generated on" line in its Repo state block');
  } else {
    if (m[1] !== 'linux') out.push(`the audit document platform is ${JSON.stringify(m[1])}, not linux`);
    if (g && typeof g === 'object' && (m[1] !== g.platform || m[2] !== g.node || m[3] !== g.container_image)) out.push('the audit document stamp disagrees with results.json');
  }
  return out;
}

const goodResults = { generated_on: { platform: 'linux', node: 'v24.1.0', container_image: 'mcr.microsoft.com/playwright:v1.61.1-noble' } };
const goodDocument = `- Repo state: \`abc1234\` (branch \`x\`)\n- Generated on: platform \`linux\`, node \`v24.1.0\`, container image \`mcr.microsoft.com/playwright:v1.61.1-noble\`\n- Run at: now\n`;

test('the committed results.json and audit document carry a linux stamp (generated by CI)', () => {
  assert.deepEqual(stampProblems(RESULTS, DOCUMENT), []);
});

test('the checker accepts a CI-shaped pair', () => {
  assert.deepEqual(stampProblems(goodResults, goodDocument), []);
});

test('ATTACK: a win32 stamp is refused', () => {
  const r = { generated_on: { ...goodResults.generated_on, platform: 'win32' } };
  const d = goodDocument.replace('platform `linux`', 'platform `win32`');
  const got = stampProblems(r, d);
  assert.ok(got.some((p) => /platform is "win32", not linux/.test(p)), JSON.stringify(got));
  assert.ok(got.some((p) => /audit document platform is "win32"/.test(p)), JSON.stringify(got));
});

test('ATTACK: a darwin stamp is refused', () => {
  const r = { generated_on: { ...goodResults.generated_on, platform: 'darwin' } };
  const d = goodDocument.replace('platform `linux`', 'platform `darwin`');
  assert.ok(stampProblems(r, d).some((p) => /not linux/.test(p)));
});

test('ATTACK: a results.json with no stamp is refused', () => {
  assert.ok(stampProblems({}, goodDocument).some((p) => /no generated_on stamp/.test(p)));
});

test('ATTACK: a document with no stamp line is refused', () => {
  assert.ok(stampProblems(goodResults, '- Repo state: `abc1234`\n').some((p) => /no "Generated on" line/.test(p)));
});

test('ATTACK: a document that disagrees with results.json is refused', () => {
  const d = goodDocument.replace('node `v24.1.0`', 'node `v22.0.0`');
  assert.ok(stampProblems(goodResults, d).some((p) => /disagrees/.test(p)));
});

// ── the generator: one stamping site, run for real ─────────────────────────────────────────────────────
function loadGeneratedOn() {
  const m = GENERATOR.match(/^function generatedOn\([\s\S]*?^}$/m);
  assert.ok(m, 'run-audit.mjs must define function generatedOn at top level');
  // eslint-disable-next-line no-new-func
  return new Function(`${m[0]}\nreturn generatedOn;`)();
}

test('generatedOn stamps platform, node and container image from the process and the environment', () => {
  const generatedOn = loadGeneratedOn();
  assert.deepEqual(
    generatedOn({ AUDIT_CONTAINER_IMAGE: 'mcr.microsoft.com/playwright:v1.61.1-noble' }, { platform: 'linux', version: 'v24.9.0' }),
    { platform: 'linux', node: 'v24.9.0', container_image: 'mcr.microsoft.com/playwright:v1.61.1-noble' },
  );
  assert.deepEqual(generatedOn({}, { platform: 'win32', version: 'v22.1.0' }), { platform: 'win32', node: 'v22.1.0', container_image: 'none' });
});

test('the stamp has exactly one construction site, and both outputs read it from results', () => {
  assert.equal((GENERATOR.match(/platform: proc\.platform/g) ?? []).length, 1, 'one place builds the stamp');
  assert.match(GENERATOR, /const results = \{ runAt: [^}]*generated_on: generatedOn\(\)/, 'results.json is stamped');
  assert.match(GENERATOR, /- Generated on: platform[^\n]*results\.generated_on\.platform/, 'the document line reads the same stamp');
});
